export type Language = 'en' | 'fr' | 'es' | 'ar' | 'ru' | 'ig'

export const languageFlags: Record<Language, { flag: string; name: string }> = {
  en: { flag: '🇬🇧', name: 'English' },
  fr: { flag: '🇫🇷', name: 'Français' },
  es: { flag: '🇪🇸', name: 'Español' },
  ar: { flag: '🇸🇦', name: 'العربية' },
  ru: { flag: '🇷🇺', name: 'Русский' },
  ig: { flag: '🇳🇬', name: 'Igbo' },
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    loading: 'Loading transaction details...',
    youWillSend: 'You will send',
    selectBlockchain: 'Select Blockchain',
    pay: 'Pay',
    cancelPayment: 'Cancel Payment',
    terms: 'Terms of service',
    privacyPolicy: 'Privacy Policy',
    byConnecting: 'By connecting to the platform, you agree to our',
    and: 'and',
    scanQr: 'Scan QR code or Copy wallet address to make payment',
    expiresIn: 'Expires in',
    minutes: 'minutes',
    imadeMadePayment: 'I have Made Payment',
    processingPayment: 'Processing Payment...',
    paymentSuccessful: 'Payment Successful',
    yourPayment: 'Your payment of',
    hasBeenSubmitted: 'has been submitted successfully',
    transactionId: 'Transaction ID',
    amount: 'Amount',
    status: 'Status',
    pendingVerification: 'Pending Verification',
    viewTransaction: 'View Transaction',
    equivalentTo: '~ equivalent to',
    selectLanguage: 'Select Your Preferred Language',
    chooseLanguage: 'Choose a language to get started',
    backToHome: 'Back to Home',
    transactions: 'Transactions',
    network: 'Network',
    walletAddress: 'Wallet Address',
    blockchainTransparency: 'Blockchain Transparency.',
    realTimeVerification: 'Decentralized Payments.',
    everyTransaction: 'Argon is 100% decentralized. Every transaction is monitored on the blockchain by custodian. All network fees covered. Unique wallet per transaction. Full key access for testing. Zero secrecy.',
    customerFees: 'Customer Fees',
    onChain: 'On-Chain',
    monitoring: 'Monitoring',
    liveMonitoring: 'Live Monitoring',
    heroPartnersTagline: 'Powering on-chain payments across leading products',
    integrateTitle: 'Accept crypto payments with Argon—no commission, live in minutes.',
    integrateSubtitle: 'Drop Argon into your site with a simple API. Argon is 100% decentralized—pay per transaction, not a cut of every payment. Plans start at $50 for 500 transactions, with custodian-covered network costs and full on-chain control.',
    integrateTabBuild: 'Setup',
    integrateTabAccept: 'Checkout',
    integrateTabSettle: 'Track',
    integrateTabBuildShort: 'Setup',
    integrateTabAcceptShort: 'Pay',
    integrateTabSettleShort: 'Track',
    integratePanelTitle: 'Developer portal',
    integrateZeroFees: 'No commission',
    integrateZeroFeesDesc: 'Per-transaction pricing from $50 / 500 txns. Custodian covers network costs.',
    integrateApiReady: 'One API',
    integrateApiReadyDesc: 'Drop in Argon and start accepting on-chain payments fast.',
    integrateLiveStatus: 'Live',
    payNow: 'Pay now',
    usdCoin: 'USD Coin',
    solana: 'Solana',
    featuresEyebrow: 'Everything on-chain',
    completeBlockchainTransparency: 'Complete Blockchain Transparency',
    realTimeOnChain: 'Argon is 100% decentralized. Every payment is monitored on-chain in real time. Network fees are covered by the custodian. Full key access for testing. Zero secrecy—no hidden processes.',
    gapEyebrow: 'WHY ARGON',
    gapHeadline: 'Other crypto gateways take a cut. Argon charges per transaction.',
    gapBodyOne: 'Most cryptocurrency checkout platforms still behave like middlemen. Coinbase Commerce, BitPay, and NOWPayments can accept digital assets—but settlements often include percentage commissions, processor markups, surprise gas fees at checkout, and limited visibility into wallet-level custody. Founders stitch together a payment API, a blockchain explorer, and a separate dashboard just to know if a USDC or USDT transfer cleared.',
    gapBodyTwoBefore: 'That commission-heavy crypto payment stack eats margin as you scale. ',
    gapBodyTwoHighlight: 'Argon is built differently:',
    gapBodyTwoAfter: ' 100% decentralized, no commission on payment volume—just transparent per-transaction pricing from $50 for 500 transactions, a single GraphQL API, custodian-covered network costs, unique wallets per payment, and live blockchain monitoring in one dashboard.',
    realTimeMonitoring: 'Real-Time Monitoring',
    everyTransactionTracked: 'Every transaction tracked and verified on the blockchain instantly by custodian.',
    custodianPaidFees: 'Custodian-Paid Fees',
    allNetworkFeeCovered: 'All network fees covered by custodian wallet. Customers pay zero blockchain costs.',
    uniqueWalletPerTransaction: 'Unique Wallet Per Transaction',
    eachPaymentGenerates: 'Each payment generates dedicated wallet address for automated, professional tracking.',
    fullKeyAccess: 'Full Key Access',
    custodianControls: 'Custodian controls private keys for real-time testing and vulnerability observation.',
    completeAuditability: 'Complete Auditability',
    allTransactions: 'All transactions and fees permanently visible on blockchain. No hidden processes.',
    instantDelayAlerts: 'Instant Delay Alerts',
    realtimeDetection: 'Real-time detection of payment delays or anomalies on-chain with automatic notification.',
    custodianPaysAllNetworkFees: 'Custodian Pays All Network Fees',
    everyBlockchainCost: 'Every blockchain cost is covered. Customers experience zero payment fees.',
    decentralizedTitle: 'Decentralized Payments',
    decentralizedBody: 'Argon is 100% Decentralized. Accept crypto on-chain with unique wallets per payment, live monitoring, and transparent per-transaction pricing—no commission cut on volume.',
    decentralizedCallout: 'Pay per transaction from $50 for 500 payments. Custodian-covered network costs. Full on-chain visibility from API to confirmation.',
    decentralizedCta: 'Get Started',
    decentralizedCheckoutTitle: 'Complete your order',
    decentralizedCheckoutProduct: 'Argon Checkout · $100.00',
    decentralizedEmailLabel: 'Email',
    decentralizedEmailValue: 'you@company.com',
    decentralizedPayWithLabel: 'Pay with',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'Network',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'Network fee covered',
    decentralizedNetworkValue: '$0.00',
    decentralizedPayButton: 'Pay $100.00',
    decentralizedSecuredBy: 'Secured by Argon · On-chain verification',
    donationsTitle: 'Donations that stay on-chain',
    donationsBody: 'Raise crypto donations with a clear target, live completion tracking, and unique wallets for every contributor—fully transparent from first gift to goal.',
    donationsCallout: 'Track donated wallets in real time. See progress against your target amount with percentage completion built into every campaign.',
    donationsCta: 'Start a donation',
    donationsCardTitle: 'Donation overview',
    donationsCampaign: 'Open Source Fund',
    donationsCampaignMeta: '128 donors · 3 wallets live',
    donationsCampaignAmount: '$7,200',
    donationsCampaignGrowth: '↑ 72% complete',
    donationsTargetLabel: 'Target amount',
    donationsTargetValue: '$10,000',
    donationsWalletsLabel: 'Goal for this campaign',
    donationsTotalLabel: 'Total raised',
    donationsTotalValue: '$7,200',
    donationsTotalPercent: '72%',
    bulkTitle: 'Bulk payments at scale',
    bulkBody: 'Pay dozens of wallets in one batch—payroll, vendors, or payouts—with live completion tracking and unique addresses for every recipient.',
    bulkCallout: 'Send once, settle many. Monitor each recipient wallet as the batch progresses toward full disbursement.',
    bulkCta: 'Create a batch',
    bulkCardTitle: 'Batch overview',
    bulkBatch: 'March payroll',
    bulkBatchMeta: '48 of 56 sent · processing',
    bulkBatchAmount: '$24,800',
    bulkBatchGrowth: '↑ 86% sent',
    bulkRecipientsLabel: 'Recipients',
    bulkRecipientsValue: '56 wallets',
    bulkRecipientsMeta: 'Target for this batch',
    bulkTotalLabel: 'Total disbursed',
    bulkTotalValue: '$24,800',
    bulkTotalPercent: '86%',
    bulkPaidLabel: 'Paid',
    bulkPendingLabel: 'Pending',
    faqEyebrow: 'Support',
    faqTitle: 'Frequently asked questions',
    faqQ1: 'Is Argon really 100% decentralized?',
    faqA1: 'Yes. Argon is 100% decentralized. Every payment is created, monitored, and verified on-chain with unique wallets per transaction and full visibility from API to confirmation.',
    faqQ2: 'How does pricing work?',
    faqA2: 'Argon does not take a commission on payment volume. You pay per transaction—plans start at $50 for 500 transactions—with custodian-covered network costs and transparent on-chain settlement.',
    faqQ3: 'Which networks and assets are supported?',
    faqA3: 'Argon supports major crypto rails including USDC on Polygon, USDT on BEP20, and SOL on Solana. Each payment gets a dedicated wallet address for clean tracking.',
    faqQ4: 'Can I run donations and bulk payouts?',
    faqA4: 'Yes. Use donation campaigns with target amounts and live completion tracking, or send bulk batches for payroll and vendor payouts with paid and pending status per wallet.',
    faqQ5: 'Who pays network / gas fees?',
    faqA5: 'Network fees are covered by the custodian wallet. Customers send the exact amount—no surprise gas deductions at checkout.',
    faqQ6: 'How do I get started?',
    faqA6: 'Create an account, grab your API key, and call the Payment mutation. You can go from setup to a live checkout link in minutes.',
    traditionalPayment: 'Traditional Payment',
    sendAmount: 'Send Amount',
    processingFee: 'Processing Fee (2-3%)',
    networkFee: 'Network Fee',
    recipientGets: 'Recipient Gets',
    argonPayment: 'Argon Payment',
    customerPays: 'Customer Pays',
    custodianCoversNetworkFee: 'Custodian Covers Network Fee',
    paid: 'Paid',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'How Transparent Payments Work',
    transparentDesc: 'Argon is 100% decentralized. Every crypto payment is created, monitored, and verified on the blockchain—with no hidden fees and full visibility from API to confirmation.',
    transparentStepOneTitle: 'Live monitoring',
    custodianMonitorsRealtime: 'The custodian tracks each payment on-chain in real time, so status updates are visible the moment a transfer moves.',
    transparentStepTwoTitle: 'Network costs covered',
    allNetworkCostsCovered: 'Gas and network fees are paid from the custodian wallet. Customers send the exact amount—no surprise deductions.',
    transparentStepThreeTitle: 'Full key access',
    fullKeyAccessForTesting: 'Access private keys for testing and verification so you can inspect wallets, confirm flows, and audit every step.',
    tryArgonNow: 'Try Argon Now',
    experienceZeroFeePayments: 'Experience zero-fee payments in action',
    paymentAmount: 'Payment Amount',
    selectCryptocurrency: 'Select Cryptocurrency',
    usdcOnPolygon: 'USDC on Polygon',
    usdtOnBep20: 'USDT on BEP20',
    totalToPay: 'Total to Pay',
    proceed: 'Proceed',
    loadingPayment: 'Loading...',
    aboutThisDemo: 'About This Demo',
    blockchainTransparentPayments: 'Blockchain transparent payments',
    custodianPaidNetworkFees: 'Custodian-paid network fees',
    realTimeOnChainVerification: 'Real-time on-chain verification',
    uniqueWallet: 'Unique wallet per transaction',
    aboutDemoTitle: 'About Argon Demo',
    demoDescription: 'This demo showcases the Argon transparent payment system. Send any amount in USDC, USDT, or SOL with zero customer fees.',
    demoWarning: 'This is a demonstration. Use testnet cryptocurrencies.',
    experienceEyebrow: 'On-chain by design',
    getStarted: 'Get Started',
    viewDocs: 'View docs',
    contact: 'Contact',
    privacyFooter: 'Privacy',
    termsFooter: 'Terms',
    checkingPayment: 'Checking Payment of',
    hangOn: 'Hang on while we Process your Payment',
    paymentSuccessfulTitle: 'Payment Successful!',
    transactionCompleted: 'Your transaction has been completed successfully.',
    amountSent: 'Amount Sent',
    networkPayment: 'Network',
    viewTransactionDetails: 'View Transaction Details',
    closeTab: 'Close Tab',
    transactionError: 'Transaction Error',
    unableLoad: 'Unable to load transaction:',
    cancelPaymentSuccess: 'Payment cancelled successfully.',
    copiedFeedback: 'Copied!',
    getInTouch: 'Get in Touch',
    contactQuestion: 'Have questions about Argon? Our team is here to help. Fill out the form below and we\'ll get back to you shortly.',
    contactOurTeam: 'Contact Our Team',
    sendMessage: 'Send us a message and we\'ll respond as soon as possible',
    thankYouMessage: 'Thank you for reaching out! Your email has been sent. We\'ll get back to you soon.',
    fullName: 'Full Name *',
    yourName: 'Your name',
    country: 'Country',
    yourCountry: 'Your country',
    emailAddress: 'Email Address *',
    yourEmail: 'your@email.com',
    subject: 'Subject *',
    aboutThis: 'What is this about?',
    message: 'Message *',
    tellUsMore: 'Tell us more about your inquiry...',
    sendMessageButton: 'Send Message',
    fillAllFields: 'Please fill in all fields',
    termsTitle: 'Terms of Service',
    termsContent: 'Terms and conditions content will appear here.',
    privacyTitle: 'Privacy Policy',
    privacyContent: 'Privacy policy content will appear here.',
    aboutTitle: 'About Us',
    cookieTitle: 'Cookie Policy',
    paymentSummary: 'Payment Summary',
    cryptocurrency: 'Cryptocurrency',
    amountToSend: 'Amount to Send',
    total: 'Total',
    custodianAccountAddress: 'Custodian Account Address *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: 'This is the account address that will receive the deposited amount. Ensure this address is correct before proceeding, as funds will be sent to this wallet.',
    gasWalletPrivateKey: 'Gas Fee Wallet Private Key',
    gasKeyPlaceholder: 'Enter private key',
    gasKeyNotRequired: 'Not required for Solana',
    solanaNote: 'Note: This field is not required for Solana transactions. Gas fees on Solana are minimal and will be handled automatically.',
    securityWarning: 'Security Warning: This wallet will pay for the gas fees required for this transaction. Ensure you have enough native tokens',
    toCovertransactionFees: 'to cover the transaction fees.',
    important: 'Important: This private key is NOT stored on our servers. For security purposes, please use a newly generated wallet. We will not be liable for any issues or losses you experience from using an existing wallet.',
    processing: 'Processing...',
    urlParameterWarning: 'URL Parameter Warning',
    detectedInvalidParameters: 'We detected some invalid parameters in the URL:',
    invalidAmount: 'Invalid Amount',
    invalidAmountMessage: 'Please enter a valid payment amount',
    invalidAmountErrorMessage: 'Amount must be a valid number greater than 0',
    enterPositiveNumber: 'Enter a positive number for the amount',
    exampleAmount: 'Example: 100 for $100 USD',
    decimalsAccepted: 'Decimals are accepted (e.g., 50.50)',
    selectAvailableNetworks: 'Select from available networks: USDC (Polygon), USDT (BSC), or SOL (Solana)',
    eachNetworkSupports: 'Each network supports different cryptocurrencies',
    goBackAndFix: 'Go Back & Fix',
    footerArgonDesc: '100% decentralized crypto payments. Blockchain transparent. Custodian-monitored. Per-transaction pricing—no commission.',
    footerResources: 'Resources',
    footerFeatures: 'Features',
    footerFeaturesLink: 'Features',
    footerPricingLink: 'Pricing',
    footerFaqLink: 'FAQ',
    footerCompany: 'Company',
    footerCommunity: 'Community',
    footerLegal: 'Legal',
    footerGithub: 'GitHub',
    footerDocumentation: 'Documentation',
    footerApiDocs: 'API Docs',
    footerTelegram: 'Telegram',
    footerSupport: 'Support',
    footerFeedback: 'Feedback',
    footerTerms: 'Terms',
    footerPrivacy: 'Privacy',
    footerAbout: 'About',
    footerCookies: 'Cookies',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'Warning',
    warningDefaultMessage: 'Please review the following:',
  },
  fr: {
    loading: 'Chargement des détails de la transaction...',
    youWillSend: 'Vous enverrez',
    selectBlockchain: 'Sélectionner la chaîne de blocs',
    pay: 'Payer',
    cancelPayment: 'Annuler le paiement',
    terms: 'Conditions de service',
    privacyPolicy: 'Politique de confidentialité',
    byConnecting: 'En vous connectant à la plateforme, vous acceptez nos',
    and: 'et',
    scanQr: 'Scannez le code QR ou copiez l\'adresse du portefeuille pour effectuer un paiement',
    expiresIn: 'Expire dans',
    minutes: 'minutes',
    imadeMadePayment: 'J\'ai effectué le paiement',
    processingPayment: 'Traitement du paiement...',
    paymentSuccessful: 'Paiement réussi',
    yourPayment: 'Votre paiement de',
    hasBeenSubmitted: 'a été soumis avec succès',
    transactionId: 'ID de transaction',
    amount: 'Montant',
    status: 'Statut',
    pendingVerification: 'En attente de vérification',
    viewTransaction: 'Afficher la transaction',
    equivalentTo: '~ équivalent à',
    selectLanguage: 'Sélectionnez votre langue préférée',
    chooseLanguage: 'Choisissez une langue pour commencer',
    backToHome: 'Retour à l\'accueil',
    transactions: 'Transactions',
    network: 'Réseau',
    walletAddress: 'Adresse du portefeuille',
    blockchainTransparency: 'Transparence Blockchain.',
    realTimeVerification: 'Paiements Décentralisés.',
    everyTransaction: 'Argon est 100 % décentralisé. Chaque transaction est surveillée sur la blockchain par le dépositaire. Tous les frais réseau couverts. Portefeuille unique par transaction. Accès complet aux clés pour les tests. Aucun secret.',
    customerFees: 'Frais Client',
    onChain: 'En Chaîne',
    monitoring: 'Surveillance',
    liveMonitoring: 'Surveillance en direct',
    heroPartnersTagline: 'Propulser les paiements on-chain sur les principaux produits',
    integrateTitle: 'Acceptez les paiements crypto avec Argon—sans commission, en ligne en quelques minutes.',
    integrateSubtitle: 'Intégrez Argon via une API simple. Argon est 100 % décentralisé—payez à la transaction, pas un pourcentage sur chaque paiement. À partir de 50 $ pour 500 transactions, avec coûts réseau couverts par le dépositaire.',
    integrateTabBuild: 'Configuration',
    integrateTabAccept: 'Paiement',
    integrateTabSettle: 'Suivi',
    integrateTabBuildShort: 'Config',
    integrateTabAcceptShort: 'Payer',
    integrateTabSettleShort: 'Suivi',
    integratePanelTitle: 'Portail développeur',
    integrateZeroFees: 'Sans commission',
    integrateZeroFeesDesc: 'Tarification à la transaction dès 50 $ / 500 txns. Le dépositaire couvre les coûts réseau.',
    integrateApiReady: 'Une API',
    integrateApiReadyDesc: 'Intégrez Argon et acceptez rapidement les paiements on-chain.',
    integrateLiveStatus: 'En ligne',
    payNow: 'Payer Maintenant',
    usdCoin: 'Pièce USD',
    solana: 'Solana',
    featuresEyebrow: 'Tout on-chain',
    completeBlockchainTransparency: 'Transparence Blockchain Complète',
    realTimeOnChain: 'Argon est 100 % décentralisé. Surveillance en temps réel sur chaîne. Frais payés par le dépositaire. Accès complet aux clés. Aucun processus caché.',
    gapEyebrow: 'POURQUOI ARGON',
    gapHeadline: 'Les autres passerelles crypto prennent une commission. Argon facture à la transaction.',
    gapBodyOne: 'La plupart des plateformes de checkout crypto agissent encore comme des intermédiaires. Coinbase Commerce, BitPay et NOWPayments acceptent les actifs numériques—mais les règlements incluent souvent des commissions en pourcentage, des majorations, des frais de gas surprises et peu de visibilité sur la garde. Les fondateurs assemblent une API, un explorateur et un tableau de bord juste pour savoir si un transfert USDC ou USDT est passé.',
    gapBodyTwoBefore: 'Cette stack à commission réduit votre marge à mesure que vous grandissez. ',
    gapBodyTwoHighlight: 'Argon fonctionne autrement :',
    gapBodyTwoAfter: ' 100 % décentralisé, aucune commission sur le volume—une tarification transparente à la transaction dès 50 $ pour 500 transactions, une API GraphQL, coûts réseau couverts par le dépositaire, portefeuilles uniques et monitoring blockchain en direct.',
    realTimeMonitoring: 'Surveillance en Temps Réel',
    everyTransactionTracked: 'Chaque transaction est suivie et vérifiée instantanément sur la blockchain par le dépositaire.',
    custodianPaidFees: 'Frais Payés par le Dépositaire',
    allNetworkFeeCovered: 'Tous les frais réseau couverts par le portefeuille du dépositaire. Les clients ne paient aucun coût blockchain.',
    uniqueWalletPerTransaction: 'Portefeuille Unique par Transaction',
    eachPaymentGenerates: 'Chaque paiement génère une adresse de portefeuille dédiée pour un suivi automatisé et professionnel.',
    fullKeyAccess: 'Accès Complet aux Clés',
    custodianControls: 'Le dépositaire contrôle les clés privées pour les tests en temps réel et l\'observation des vulnérabilités.',
    completeAuditability: 'Traçabilité Complète',
    allTransactions: 'Toutes les transactions et frais sont permanentement visibles sur la blockchain. Aucun processus caché.',
    instantDelayAlerts: 'Alertes de Retard Instantanées',
    realtimeDetection: 'Détection en temps réel des retards de paiement ou des anomalies en chaîne avec notification automatique.',
    custodianPaysAllNetworkFees: 'Le Dépositaire Paie Tous les Frais Réseau',
    everyBlockchainCost: 'Chaque coût blockchain est couvert. Les clients connaissent zéro frais de paiement.',
    decentralizedTitle: 'Paiements Décentralisés',
    decentralizedBody: 'Argon est 100 % Décentralisé. Acceptez la crypto on-chain avec des portefeuilles uniques, un suivi en direct et une tarification transparente à la transaction—sans commission sur le volume.',
    decentralizedCallout: 'Payez à la transaction dès 50 $ pour 500 paiements. Coûts réseau couverts par le dépositaire. Visibilité on-chain de l’API à la confirmation.',
    decentralizedCta: 'Commencer',
    decentralizedCheckoutTitle: 'Finalisez votre commande',
    decentralizedCheckoutProduct: 'Argon Checkout · 100,00 $',
    decentralizedEmailLabel: 'E-mail',
    decentralizedEmailValue: 'vous@entreprise.com',
    decentralizedPayWithLabel: 'Payer avec',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'Réseau',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'Frais réseau couverts',
    decentralizedNetworkValue: '0,00 $',
    decentralizedPayButton: 'Payer 100,00 $',
    decentralizedSecuredBy: 'Sécurisé par Argon · Vérification on-chain',
    donationsTitle: 'Des dons qui restent on-chain',
    donationsBody: 'Collectez des dons crypto avec un objectif clair, un suivi de progression en direct et des portefeuilles uniques pour chaque contributeur—transparent du premier don à l’objectif.',
    donationsCallout: 'Suivez les portefeuilles donateurs en temps réel. Voyez la progression vers votre montant cible avec un pourcentage de complétion intégré.',
    donationsCta: 'Lancer un don',
    donationsCardTitle: 'Aperçu des dons',
    donationsCampaign: 'Fonds open source',
    donationsCampaignMeta: '128 donateurs · 3 portefeuilles actifs',
    donationsCampaignAmount: '7 200 $',
    donationsCampaignGrowth: '↑ 72 % atteint',
    donationsTargetLabel: 'Montant cible',
    donationsTargetValue: '10 000 $',
    donationsWalletsLabel: 'Objectif de la campagne',
    donationsTotalLabel: 'Total collecté',
    donationsTotalValue: '7 200 $',
    donationsTotalPercent: '72 %',
    bulkTitle: 'Paiements groupés à l’échelle',
    bulkBody: 'Payez des dizaines de portefeuilles en un lot—paie, fournisseurs ou versements—avec suivi en direct et adresses uniques pour chaque destinataire.',
    bulkCallout: 'Envoyez une fois, réglez plusieurs. Suivez chaque portefeuille destinataire à mesure que le lot progresse.',
    bulkCta: 'Créer un lot',
    bulkCardTitle: 'Aperçu du lot',
    bulkBatch: 'Paie de mars',
    bulkBatchMeta: '48 sur 56 envoyés · en cours',
    bulkBatchAmount: '24 800 $',
    bulkBatchGrowth: '↑ 86 % envoyé',
    bulkRecipientsLabel: 'Destinataires',
    bulkRecipientsValue: '56 portefeuilles',
    bulkRecipientsMeta: 'Objectif de ce lot',
    bulkTotalLabel: 'Total versé',
    bulkTotalValue: '24 800 $',
    bulkTotalPercent: '86 %',
    bulkPaidLabel: 'Payé',
    bulkPendingLabel: 'En attente',
    faqEyebrow: 'Support',
    faqTitle: 'Questions fréquentes',
    faqQ1: 'Argon est-il vraiment 100 % décentralisé ?',
    faqA1: 'Oui. Argon est 100 % décentralisé. Chaque paiement est créé, suivi et vérifié on-chain avec des portefeuilles uniques et une visibilité totale de l’API à la confirmation.',
    faqQ2: 'Comment fonctionne la tarification ?',
    faqA2: 'Argon ne prend pas de commission sur le volume. Vous payez à la transaction—à partir de 50 $ pour 500 transactions—avec coûts réseau couverts et règlement on-chain transparent.',
    faqQ3: 'Quels réseaux et actifs sont pris en charge ?',
    faqA3: 'Argon prend en charge USDC sur Polygon, USDT sur BEP20 et SOL sur Solana. Chaque paiement reçoit une adresse de portefeuille dédiée.',
    faqQ4: 'Puis-je gérer dons et paiements groupés ?',
    faqA4: 'Oui. Lancez des campagnes de dons avec objectif et progression, ou des lots pour paie et fournisseurs avec statut payé / en attente par portefeuille.',
    faqQ5: 'Qui paie les frais réseau / gas ?',
    faqA5: 'Les frais réseau sont couverts par le portefeuille du dépositaire. Les clients envoient le montant exact—sans gas surprise.',
    faqQ6: 'Comment commencer ?',
    faqA6: 'Créez un compte, récupérez votre clé API et appelez la mutation Payment. Du setup au lien de checkout en quelques minutes.',
    traditionalPayment: 'Paiement Traditionnel',
    sendAmount: 'Montant à Envoyer',
    processingFee: 'Frais de Traitement (2-3%)',
    networkFee: 'Frais Réseau',
    recipientGets: 'Le Bénéficiaire Reçoit',
    argonPayment: 'Paiement Argon',
    customerPays: 'Le Client Paie',
    custodianCoversNetworkFee: 'Le Dépositaire Couvre les Frais Réseau',
    paid: 'Payé',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'Comment Fonctionnent les Paiements Transparents',
    transparentDesc: 'Argon est 100 % décentralisé. Chaque paiement crypto est créé, suivi et vérifié on-chain—sans frais cachés et avec une visibilité totale de l’API à la confirmation.',
    transparentStepOneTitle: 'Suivi en direct',
    custodianMonitorsRealtime: 'Le dépositaire suit chaque paiement on-chain en temps réel, pour que le statut soit visible dès qu’un transfert avance.',
    transparentStepTwoTitle: 'Coûts réseau couverts',
    allNetworkCostsCovered: 'Les frais de gas et réseau sont payés par le portefeuille du dépositaire. Les clients envoient le montant exact—sans déduction surprise.',
    transparentStepThreeTitle: 'Accès complet aux clés',
    fullKeyAccessForTesting: 'Accédez aux clés privées pour tester et vérifier, inspecter les portefeuilles, confirmer les flux et auditer chaque étape.',
    tryArgonNow: 'Essayez Argon Maintenant',
    experienceZeroFeePayments: 'Expérience des paiements sans frais en action',
    paymentAmount: 'Montant du Paiement',
    selectCryptocurrency: 'Sélectionner Crypto-monnaie',
    usdcOnPolygon: 'USDC sur Polygon',
    usdtOnBep20: 'USDT sur BEP20',
    totalToPay: 'Total à Payer',
    proceed: 'Continuer',
    loadingPayment: 'Chargement...',
    aboutThisDemo: 'À Propos de Cette Démo',
    blockchainTransparentPayments: 'Paiements transparents blockchain',
    custodianPaidNetworkFees: 'Frais réseau payés par le dépositaire',
    realTimeOnChainVerification: 'Vérification en temps réel sur la chaîne',
    uniqueWallet: 'Portefeuille unique par transaction',
    aboutDemoTitle: 'À Propos de la Démo Argon',
    demoDescription: 'Cette démo présente le système de paiement transparent Argon. Envoyez n\'importe quel montant en USDC, USDT ou SOL sans frais client.',
    demoWarning: 'Ceci est une démonstration. Utilisez des crypto-monnaies testnet.',
    experienceEyebrow: 'On-chain par conception',
    getStarted: 'Commencer',
    viewDocs: 'Voir la documentation',
    contact: 'Contact',
    privacyFooter: 'Confidentialité',
    termsFooter: 'Conditions',
    checkingPayment: 'Vérification du Paiement de',
    hangOn: 'Attendez pendant que nous traitons votre paiement',
    paymentSuccessfulTitle: 'Paiement Réussi!',
    transactionCompleted: 'Votre transaction a été complétée avec succès.',
    amountSent: 'Montant Envoyé',
    networkPayment: 'Réseau',
    viewTransactionDetails: 'Afficher les détails de la transaction',
    closeTab: 'Fermer l\'onglet',
    transactionError: 'Erreur de Transaction',
    unableLoad: 'Impossible de charger la transaction:',
    cancelPaymentSuccess: 'Paiement annulé avec succès.',
    copiedFeedback: 'Copié!',
    getInTouch: 'Nous Contacter',
    contactQuestion: 'Vous avez des questions sur Argon? Notre équipe est là pour vous aider. Remplissez le formulaire ci-dessous et nous vous répondrons rapidement.',
    contactOurTeam: 'Contactez Notre Équipe',
    sendMessage: 'Envoyez-nous un message et nous répondrons dès que possible',
    thankYouMessage: 'Merci de nous avoir contactés! Votre email a été envoyé. Nous vous répondrons bientôt.',
    fullName: 'Nom Complet *',
    yourName: 'Votre nom',
    country: 'Pays',
    yourCountry: 'Votre pays',
    emailAddress: 'Adresse Email *',
    yourEmail: 'votre@email.com',
    subject: 'Sujet *',
    aboutThis: 'De quoi s\'agit-il?',
    message: 'Message *',
    tellUsMore: 'Dites-nous en plus sur votre demande...',
    sendMessageButton: 'Envoyer le Message',
    fillAllFields: 'Veuillez remplir tous les champs',
    termsTitle: 'Conditions d\'Utilisation',
    termsContent: 'Le contenu des conditions générales apparaîtra ici.',
    privacyTitle: 'Politique de Confidentialité',
    privacyContent: 'Le contenu de la politique de confidentialité apparaîtra ici.',
    aboutTitle: 'À propos',
    cookieTitle: 'Politique de cookies',
    paymentSummary: 'Résumé du Paiement',
    cryptocurrency: 'Crypto-monnaie',
    amountToSend: 'Montant à Envoyer',
    total: 'Total',
    custodianAccountAddress: 'Adresse du Compte Dépositaire *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: "Ceci est l'adresse du compte qui recevra le montant déposé. Assurez-vous que cette adresse est correcte avant de continuer, car les fonds seront envoyés à ce portefeuille.",
    gasWalletPrivateKey: 'Clé Privée du Portefeuille Frais Gaz',
    gasKeyPlaceholder: 'Entrez la clé privée',
    gasKeyNotRequired: 'Non requis pour Solana',
    solanaNote: "Remarque: Ce champ n'est pas requis pour les transactions Solana. Les frais gaz sur Solana sont minimes et seront traités automatiquement.",
    securityWarning: "Avertissement de Sécurité: Ce portefeuille paiera les frais gaz requis pour cette transaction. Assurez-vous d'avoir suffisamment de jetons natifs",
    toCovertransactionFees: 'pour couvrir les frais de transaction.',
    important: "Important: Cette clé privée n'est PAS stockée sur nos serveurs. À des fins de sécurité, veuillez utiliser un portefeuille nouvellement généré. Nous ne serons pas responsables des problèmes ou pertes que vous subirez en utilisant un portefeuille existant.",
    processing: 'Traitement...',
    urlParameterWarning: 'Avertissement de Paramètre URL',
    detectedInvalidParameters: "Nous avons détecté des paramètres invalides dans l'URL:",
    invalidAmount: 'Montant Invalide',
    invalidAmountMessage: 'Veuillez entrer un montant de paiement valide',
    invalidAmountErrorMessage: 'Le montant doit être un nombre valide supérieur à 0',
    enterPositiveNumber: 'Entrez un nombre positif pour le montant',
    exampleAmount: 'Exemple: 100 pour 100 $ USD',
    decimalsAccepted: 'Les décimales sont acceptées (p. ex. 50,50)',
    selectAvailableNetworks: 'Sélectionnez parmi les réseaux disponibles: USDC (Polygon), USDT (BSC) ou SOL (Solana)',
    eachNetworkSupports: 'Chaque réseau prend en charge différentes crypto-monnaies',
    goBackAndFix: 'Retour & Corriger',
    footerArgonDesc: 'Paiements crypto 100 % décentralisés. Transparents on-chain. Surveillés par dépositaire. Tarification à la transaction—sans commission.',
    footerResources: 'Ressources',
    footerFeatures: 'Fonctionnalités',
    footerFeaturesLink: 'Fonctionnalités',
    footerPricingLink: 'Tarifs',
    footerFaqLink: 'FAQ',
    footerCompany: 'Entreprise',
    footerCommunity: 'Communauté',
    footerLegal: 'Légal',
    footerGithub: 'GitHub',
    footerDocumentation: 'Documentation',
    footerApiDocs: 'Docs API',
    footerTelegram: 'Telegram',
    footerSupport: 'Assistance',
    footerFeedback: 'Retour',
    footerTerms: 'Conditions',
    footerPrivacy: 'Confidentialité',
    footerAbout: 'À propos',
    footerCookies: 'Cookies',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'Avertissement',
    warningDefaultMessage: 'Veuillez examiner ce qui suit:',
  },
  es: {
    loading: 'Cargando detalles de la transacción...',
    youWillSend: 'Enviará',
    selectBlockchain: 'Seleccionar blockchain',
    pay: 'Pagar',
    cancelPayment: 'Cancelar pago',
    terms: 'Términos de servicio',
    privacyPolicy: 'Política de privacidad',
    byConnecting: 'Al conectarse a la plataforma, acepta nuestros',
    and: 'y',
    scanQr: 'Escanee el código QR o copie la dirección de la billetera para realizar el pago',
    expiresIn: 'Expira en',
    minutes: 'minutos',
    imadeMadePayment: 'He realizado el pago',
    processingPayment: 'Procesando pago...',
    paymentSuccessful: 'Pago exitoso',
    yourPayment: 'Su pago de',
    hasBeenSubmitted: 'ha sido enviado exitosamente',
    transactionId: 'ID de transacción',
    amount: 'Cantidad',
    status: 'Estado',
    pendingVerification: 'Pendiente de verificación',
    viewTransaction: 'Ver transacción',
    equivalentTo: '~ equivalente a',
    selectLanguage: 'Seleccione su idioma preferido',
    chooseLanguage: 'Elige un idioma para comenzar',
    backToHome: 'Volver al inicio',
    transactions: 'Transacciones',
    network: 'Red',
    walletAddress: 'Dirección de billetera',
    blockchainTransparency: 'Transparencia Blockchain.',
    realTimeVerification: 'Pagos Descentralizados.',
    everyTransaction: 'Argon es 100% descentralizado. Cada transacción se monitorea en blockchain por custodia. Todos los costos de red cubiertos. Billetera única por transacción. Acceso completo a claves para pruebas. Cero secreto.',
    customerFees: 'Tarifas de Cliente',
    onChain: 'En Cadena',
    monitoring: 'Monitoreo',
    liveMonitoring: 'Monitoreo en vivo',
    heroPartnersTagline: 'Impulsando pagos on-chain en los principales productos',
    integrateTitle: 'Acepta pagos cripto con Argon—sin comisión, en vivo en minutos.',
    integrateSubtitle: 'Integra Argon con una API sencilla. Argon es 100% descentralizado—paga por transacción, no un porcentaje de cada pago. Desde $50 por 500 transacciones, con costos de red cubiertos por el custodio.',
    integrateTabBuild: 'Configuración',
    integrateTabAccept: 'Checkout',
    integrateTabSettle: 'Seguimiento',
    integrateTabBuildShort: 'Config',
    integrateTabAcceptShort: 'Pagar',
    integrateTabSettleShort: 'Seguir',
    integratePanelTitle: 'Portal de desarrolladores',
    integrateZeroFees: 'Sin comisión',
    integrateZeroFeesDesc: 'Precio por transacción desde $50 / 500 txns. El custodio cubre los costos de red.',
    integrateApiReady: 'Una API',
    integrateApiReadyDesc: 'Integra Argon y empieza a aceptar pagos on-chain rápido.',
    integrateLiveStatus: 'En vivo',
    payNow: 'Pagar Ahora',
    usdCoin: 'Moneda USD',
    solana: 'Solana',
    featuresEyebrow: 'Todo on-chain',
    completeBlockchainTransparency: 'Transparencia Blockchain Completa',
    realTimeOnChain: 'Argon es 100% descentralizado. Monitoreo en tiempo real en cadena. Tarifas pagadas por custodia. Acceso completo a claves. Sin procesos ocultos.',
    gapEyebrow: 'POR QUÉ ARGON',
    gapHeadline: 'Otras pasarelas cripto se llevan una comisión. Argon cobra por transacción.',
    gapBodyOne: 'La mayoría de las plataformas de checkout cripto siguen actuando como intermediarios. Coinbase Commerce, BitPay y NOWPayments aceptan activos digitales, pero las liquidaciones suelen incluir comisiones porcentuales, markups, gas sorpresa y poca visibilidad de custodia. Los fundadores unen una API, un explorador y un panel solo para saber si un envío USDC o USDT se confirmó.',
    gapBodyTwoBefore: 'Ese stack con comisiones reduce tu margen al escalar. ',
    gapBodyTwoHighlight: 'Argon funciona distinto:',
    gapBodyTwoAfter: ' 100% descentralizado, sin comisión sobre el volumen—precio transparente por transacción desde $50 por 500 transacciones, una API GraphQL, costos de red cubiertos por el custodio, wallets únicos y monitoreo blockchain en vivo.',
    realTimeMonitoring: 'Monitoreo en Tiempo Real',
    everyTransactionTracked: 'Cada transacción se rastrea y verifica instantáneamente en blockchain por custodia.',
    custodianPaidFees: 'Tarifas Pagadas por Custodia',
    allNetworkFeeCovered: 'Todos los costos de red cubiertos por billetera de custodia. Los clientes no pagan costos de blockchain.',
    uniqueWalletPerTransaction: 'Billetera Única por Transacción',
    eachPaymentGenerates: 'Cada pago genera una dirección de billetera dedicada para rastreo automatizado y profesional.',
    fullKeyAccess: 'Acceso Completo a Claves',
    custodianControls: 'La custodia controla claves privadas para pruebas en tiempo real y observación de vulnerabilidades.',
    completeAuditability: 'Auditabilidad Completa',
    allTransactions: 'Todas las transacciones y tarifas son permanentemente visibles en blockchain. Sin procesos ocultos.',
    instantDelayAlerts: 'Alertas de Retraso Instantáneas',
    realtimeDetection: 'Detección en tiempo real de retrasos de pago o anomalías en cadena con notificación automática.',
    custodianPaysAllNetworkFees: 'La Custodia Paga Todos los Costos de Red',
    everyBlockchainCost: 'Cada costo de blockchain está cubierto. Los clientes experimentan cero tarifas de pago.',
    decentralizedTitle: 'Pagos Descentralizados',
    decentralizedBody: 'Argon es 100% Descentralizado. Acepta cripto on-chain con wallets únicos por pago, monitoreo en vivo y precio transparente por transacción—sin comisión sobre el volumen.',
    decentralizedCallout: 'Paga por transacción desde $50 por 500 pagos. Costos de red cubiertos por el custodio. Visibilidad on-chain de la API a la confirmación.',
    decentralizedCta: 'Comenzar',
    decentralizedCheckoutTitle: 'Completa tu pedido',
    decentralizedCheckoutProduct: 'Argon Checkout · $100.00',
    decentralizedEmailLabel: 'Correo',
    decentralizedEmailValue: 'tu@empresa.com',
    decentralizedPayWithLabel: 'Pagar con',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'Red',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'Tarifa de red cubierta',
    decentralizedNetworkValue: '$0.00',
    decentralizedPayButton: 'Pagar $100.00',
    decentralizedSecuredBy: 'Protegido por Argon · Verificación on-chain',
    donationsTitle: 'Donaciones que permanecen on-chain',
    donationsBody: 'Recauda donaciones cripto con un objetivo claro, seguimiento de progreso en vivo y wallets únicos por contribuyente—transparente del primer aporte a la meta.',
    donationsCallout: 'Rastrea wallets donados en tiempo real. Ve el avance hacia tu monto objetivo con el porcentaje de completado en cada campaña.',
    donationsCta: 'Iniciar una donación',
    donationsCardTitle: 'Resumen de donaciones',
    donationsCampaign: 'Fondo open source',
    donationsCampaignMeta: '128 donantes · 3 wallets activos',
    donationsCampaignAmount: '$7,200',
    donationsCampaignGrowth: '↑ 72% completo',
    donationsTargetLabel: 'Monto objetivo',
    donationsTargetValue: '$10,000',
    donationsWalletsLabel: 'Meta de esta campaña',
    donationsTotalLabel: 'Total recaudado',
    donationsTotalValue: '$7,200',
    donationsTotalPercent: '72%',
    bulkTitle: 'Pagos masivos a escala',
    bulkBody: 'Paga a docenas de wallets en un lote—nómina, proveedores o payouts—con seguimiento en vivo y direcciones únicas por destinatario.',
    bulkCallout: 'Envía una vez, liquida muchos. Monitorea cada wallet destinatario mientras el lote avanza hacia el desembolso completo.',
    bulkCta: 'Crear un lote',
    bulkCardTitle: 'Resumen del lote',
    bulkBatch: 'Nómina de marzo',
    bulkBatchMeta: '48 de 56 enviados · procesando',
    bulkBatchAmount: '$24,800',
    bulkBatchGrowth: '↑ 86% enviado',
    bulkRecipientsLabel: 'Destinatarios',
    bulkRecipientsValue: '56 wallets',
    bulkRecipientsMeta: 'Meta de este lote',
    bulkTotalLabel: 'Total desembolsado',
    bulkTotalValue: '$24,800',
    bulkTotalPercent: '86%',
    bulkPaidLabel: 'Pagado',
    bulkPendingLabel: 'Pendiente',
    faqEyebrow: 'Soporte',
    faqTitle: 'Preguntas frecuentes',
    faqQ1: '¿Argon es realmente 100% descentralizado?',
    faqA1: 'Sí. Argon es 100% descentralizado. Cada pago se crea, monitorea y verifica on-chain con wallets únicos y visibilidad total de la API a la confirmación.',
    faqQ2: '¿Cómo funciona el precio?',
    faqA2: 'Argon no cobra comisión sobre el volumen. Pagas por transacción—desde $50 por 500 transacciones—con costos de red cubiertos y liquidación on-chain transparente.',
    faqQ3: '¿Qué redes y activos se admiten?',
    faqA3: 'Argon admite USDC en Polygon, USDT en BEP20 y SOL en Solana. Cada pago obtiene una dirección de wallet dedicada.',
    faqQ4: '¿Puedo hacer donaciones y pagos masivos?',
    faqA4: 'Sí. Campañas de donación con meta y progreso en vivo, o lotes para nómina y proveedores con estado pagado / pendiente por wallet.',
    faqQ5: '¿Quién paga las tarifas de red / gas?',
    faqA5: 'Las tarifas de red las cubre la billetera del custodio. Los clientes envían el monto exacto—sin gas sorpresa.',
    faqQ6: '¿Cómo empiezo?',
    faqA6: 'Crea una cuenta, obtén tu API key y llama a la mutación Payment. Del setup al link de checkout en minutos.',
    traditionalPayment: 'Pago Tradicional',
    sendAmount: 'Cantidad a Enviar',
    processingFee: 'Tarifa de Procesamiento (2-3%)',
    networkFee: 'Tarifa de Red',
    recipientGets: 'El Destinatario Recibe',
    argonPayment: 'Pago Argon',
    customerPays: 'El Cliente Paga',
    custodianCoversNetworkFee: 'La Custodia Cubre la Tarifa de Red',
    paid: 'Pagado',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'Cómo Funcionan los Pagos Transparentes',
    transparentDesc: 'Argon es 100% descentralizado. Cada pago cripto se crea, monitorea y verifica on-chain—sin tarifas ocultas y con visibilidad total desde la API hasta la confirmación.',
    transparentStepOneTitle: 'Monitoreo en vivo',
    custodianMonitorsRealtime: 'El custodio rastrea cada pago on-chain en tiempo real, para que el estado sea visible en cuanto se mueve una transferencia.',
    transparentStepTwoTitle: 'Costos de red cubiertos',
    allNetworkCostsCovered: 'El gas y las tarifas de red los paga la billetera del custodio. Los clientes envían el monto exacto—sin descuentos sorpresa.',
    transparentStepThreeTitle: 'Acceso completo a claves',
    fullKeyAccessForTesting: 'Accede a claves privadas para probar y verificar, inspeccionar wallets, confirmar flujos y auditar cada paso.',
    tryArgonNow: 'Prueba Argon Ahora',
    experienceZeroFeePayments: 'Experiencia de pagos sin tarifas en acción',
    paymentAmount: 'Cantidad de Pago',
    selectCryptocurrency: 'Seleccionar Criptomoneda',
    usdcOnPolygon: 'USDC en Polygon',
    usdtOnBep20: 'USDT en BEP20',
    totalToPay: 'Total a Pagar',
    proceed: 'Proceder',
    loadingPayment: 'Cargando...',
    aboutThisDemo: 'Acerca de Esta Demostración',
    blockchainTransparentPayments: 'Pagos transparentes blockchain',
    custodianPaidNetworkFees: 'Tarifas de red pagadas por custodia',
    realTimeOnChainVerification: 'Verificación en tiempo real en cadena',
    uniqueWallet: 'Billetera única por transacción',
    aboutDemoTitle: 'Acerca de la Demostración Argon',
    demoDescription: 'Esta demostración muestra el sistema de pago transparente Argon. Envíe cualquier cantidad en USDC, USDT o SOL sin tarifas de cliente.',
    demoWarning: 'Esta es una demostración. Utilice criptomonedas de testnet.',
    experienceEyebrow: 'On-chain por diseño',
    getStarted: 'Empezar',
    viewDocs: 'Ver documentación',
    contact: 'Contacto',
    privacyFooter: 'Privacidad',
    termsFooter: 'Condiciones',
    checkingPayment: 'Verificando Pago de',
    hangOn: 'Espere mientras procesamos su pago',
    paymentSuccessfulTitle: '¡Pago Exitoso!',
    transactionCompleted: 'Su transacción se ha completado con éxito.',
    amountSent: 'Cantidad Enviada',
    networkPayment: 'Red',
    viewTransactionDetails: 'Ver Detalles de la Transacción',
    closeTab: 'Cerrar Pestaña',
    transactionError: 'Error de Transacción',
    unableLoad: 'No se puede cargar la transacción:',
    cancelPaymentSuccess: 'Pago cancelado con éxito.',
    copiedFeedback: '¡Copiado!',
    getInTouch: 'Contáctenos',
    contactQuestion: '¿Tiene preguntas sobre Argon? Nuestro equipo está aquí para ayudar. Complete el formulario a continuación y nos comunicaremos con usted pronto.',
    contactOurTeam: 'Contacte a Nuestro Equipo',
    sendMessage: 'Envíenos un mensaje y responderemos lo antes posible',
    thankYouMessage: '¡Gracias por comunicarse! Su email ha sido enviado. Pronto nos comunicaremos con usted.',
    fullName: 'Nombre Completo *',
    yourName: 'Tu nombre',
    country: 'País',
    yourCountry: 'Tu país',
    emailAddress: 'Dirección de Correo Electrónico *',
    yourEmail: 'tu@email.com',
    subject: 'Asunto *',
    aboutThis: '¿De qué se trata?',
    message: 'Mensaje *',
    tellUsMore: 'Cuéntenos más sobre su consulta...',
    sendMessageButton: 'Enviar Mensaje',
    fillAllFields: 'Por favor complete todos los campos',
    termsTitle: 'Términos de Servicio',
    termsContent: 'El contenido de los términos y condiciones aparecerá aquí.',
    privacyTitle: 'Política de Privacidad',
    privacyContent: 'El contenido de la política de privacidad aparecerá aquí.',
    aboutTitle: 'Sobre nosotros',
    cookieTitle: 'Política de cookies',
    paymentSummary: 'Resumen del Pago',
    cryptocurrency: 'Criptomoneda',
    amountToSend: 'Cantidad a Enviar',
    total: 'Total',
    custodianAccountAddress: 'Dirección de Cuenta del Custodio *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: 'Esta es la dirección de la cuenta que recibirá el monto depositado. Asegúrese de que esta dirección sea correcta antes de continuar, ya que los fondos se enviarán a esta billetera.',
    gasWalletPrivateKey: 'Clave Privada de Billetera de Tarifa de Gas',
    gasKeyPlaceholder: 'Ingrese la clave privada',
    gasKeyNotRequired: 'No es necesario para Solana',
    solanaNote: 'Nota: Este campo no es necesario para las transacciones de Solana. Las tarifas de gas en Solana son mínimas y se manejarán automáticamente.',
    securityWarning: 'Advertencia de Seguridad: Esta billetera pagará las tarifas de gas requeridas para esta transacción. Asegúrese de tener suficientes tokens nativos',
    toCovertransactionFees: 'para cubrir las tarifas de transacción.',
    important: 'Importante: Esta clave privada NO se almacena en nuestros servidores. Por razones de seguridad, utilice una billetera recién generada. No seremos responsables de ningún problema o pérdida que experimente al usar una billetera existente.',
    processing: 'Procesando...',
    urlParameterWarning: 'Advertencia de Parámetro URL',
    detectedInvalidParameters: 'Detectamos algunos parámetros no válidos en la URL:',
    invalidAmount: 'Cantidad Inválida',
    invalidAmountMessage: 'Ingrese un monto de pago válido',
    invalidAmountErrorMessage: 'El monto debe ser un número válido mayor que 0',
    enterPositiveNumber: 'Ingrese un número positivo para el monto',
    exampleAmount: 'Ejemplo: 100 para $100 USD',
    decimalsAccepted: 'Se aceptan decimales (p. ej. 50,50)',
    selectAvailableNetworks: 'Seleccione entre las redes disponibles: USDC (Polygon), USDT (BSC) o SOL (Solana)',
    eachNetworkSupports: 'Cada red admite diferentes criptomonedas',
    goBackAndFix: 'Volver y Corregir',
    footerArgonDesc: 'Pagos cripto 100% descentralizados. Transparentes on-chain. Monitoreados por custodio. Precio por transacción—sin comisión.',
    footerResources: 'Recursos',
    footerFeatures: 'Funciones',
    footerFeaturesLink: 'Funciones',
    footerPricingLink: 'Precios',
    footerFaqLink: 'FAQ',
    footerCompany: 'Empresa',
    footerCommunity: 'Comunidad',
    footerLegal: 'Legal',
    footerGithub: 'GitHub',
    footerDocumentation: 'Documentación',
    footerApiDocs: 'Docs API',
    footerTelegram: 'Telegram',
    footerSupport: 'Soporte',
    footerFeedback: 'Comentarios',
    footerTerms: 'Términos',
    footerPrivacy: 'Privacidad',
    footerAbout: 'Sobre nosotros',
    footerCookies: 'Cookies',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'Advertencia',
    warningDefaultMessage: 'Por favor revise lo siguiente:',
  },
  ar: {
    loading: 'جاري تحميل تفاصيل المعاملة...',
    youWillSend: 'سوف ترسل',
    selectBlockchain: 'اختر البلوكتشين',
    pay: 'ادفع',
    cancelPayment: 'إلغاء الدفع',
    terms: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    byConnecting: 'بالاتصال بالمنصة، فإنك توافق على',
    and: 'و',
    scanQr: 'امسح رمز QR أو انسخ عنوان المحفظة لإجراء الدفع',
    expiresIn: 'ينتهي الصلاحية في',
    minutes: 'دقائق',
    imadeMadePayment: 'لقد قمت بالدفع',
    processingPayment: 'معالجة الدفع...',
    paymentSuccessful: 'الدفع نجح',
    yourPayment: 'دفعتك من',
    hasBeenSubmitted: 'تم تقديمها بنجاح',
    transactionId: 'معرف المعاملة',
    amount: 'المبلغ',
    status: 'الحالة',
    pendingVerification: 'قيد التحقق',
    viewTransaction: 'عرض المعاملة',
    equivalentTo: '~ ما يعادل',
    selectLanguage: 'اختر لغتك المفضلة',
    chooseLanguage: 'اختر لغة للبدء',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    transactions: 'المعاملات',
    network: 'الشبكة',
    walletAddress: 'عنوان المحفظة',
    blockchainTransparency: 'شفافية البلوكتشين.',
    realTimeVerification: 'مدفوعات لامركزية.',
    everyTransaction: 'Argon لامركزي بنسبة 100%. تتم مراقبة كل معاملة على blockchain بواسطة الحارس. جميع رسوم الشبكة مغطاة. محفظة فريدة لكل معاملة. وصول كامل للمفاتيح للاختبار. بدون أسرار.',
    customerFees: 'رسوم العملاء',
    onChain: 'على السلسلة',
    monitoring: 'المراقبة',
    liveMonitoring: 'مراقبة مباشرة',
    heroPartnersTagline: 'تمكين المدفوعات على السلسلة عبر المنتجات الرائدة',
    integrateTitle: 'اقبل مدفوعات العملات المشفرة مع Argon—بدون عمولة، وتعمل خلال دقائق.',
    integrateSubtitle: 'أضف Argon عبر واجهة بسيطة. Argon لامركزي بنسبة 100%—ادفع لكل معاملة وليس نسبة من كل دفعة. تبدأ الخطط من 50$ مقابل 500 معاملة، مع تغطية الحارس لتكاليف الشبكة.',
    integrateTabBuild: 'الإعداد',
    integrateTabAccept: 'الدفع',
    integrateTabSettle: 'التتبع',
    integrateTabBuildShort: 'إعداد',
    integrateTabAcceptShort: 'دفع',
    integrateTabSettleShort: 'تتبع',
    integratePanelTitle: 'بوابة المطورين',
    integrateZeroFees: 'بدون عمولة',
    integrateZeroFeesDesc: 'تسعير لكل معاملة من 50$ / 500 معاملة. يغطي الحارس تكاليف الشبكة.',
    integrateApiReady: 'واجهة واحدة',
    integrateApiReadyDesc: 'أضف Argon وابدأ بقبول المدفوعات على السلسلة بسرعة.',
    integrateLiveStatus: 'مباشر',
    payNow: 'ادفع الآن',
    usdCoin: 'عملة يو إس دي',
    solana: 'سولانا',
    featuresEyebrow: 'كل شيء على السلسلة',
    completeBlockchainTransparency: 'شفافية البلوكتشين الكاملة',
    realTimeOnChain: 'Argon لامركزي بنسبة 100%. مراقبة على السلسلة في الوقت الفعلي. رسوم مدفوعة من قبل الحارس. وصول كامل للمفاتيح. بدون عمليات مخفية.',
    gapEyebrow: 'لماذا ARGON',
    gapHeadline: 'بوابات الدفع الأخرى تأخذ عمولة. Argon يحاسب لكل معاملة.',
    gapBodyOne: 'معظم منصات الدفع بالعملات المشفرة ما زالت تعمل كوسطاء. Coinbase Commerce وBitPay وNOWPayments تقبل الأصول الرقمية—لكن التسويات غالباً تتضمن عمولات نسبية وهوامش ورسوم غاز مفاجئة ورؤية محدودة للحفظ. يجمع المؤسسون بين واجهة دفع ومستكشف ولوحة منفصلة فقط لمعرفة إن اكتمل تحويل USDC أو USDT.',
    gapBodyTwoBefore: 'نظام العمولات هذا يأكل هامشك مع النمو. ',
    gapBodyTwoHighlight: 'Argon مختلف:',
    gapBodyTwoAfter: ' لامركزي 100%، بدون عمولة على حجم المدفوعات—تسعير شفاف لكل معاملة يبدأ من 50$ مقابل 500 معاملة، وواجهة GraphQL واحدة، وتكاليف الشبكة يغطيها الحارس، ومحفظة فريدة لكل دفعة، ومراقبة مباشرة من لوحة واحدة.',
    realTimeMonitoring: 'المراقبة في الوقت الفعلي',
    everyTransactionTracked: 'يتم تتبع كل معاملة والتحقق منها فوراً على blockchain بواسطة الحارس.',
    custodianPaidFees: 'الرسوم المدفوعة من قبل الحارس',
    allNetworkFeeCovered: 'جميع رسوم الشبكة مغطاة بواسطة محفظة الحارس. العملاء لا يدفعون أي تكاليف blockchain.',
    uniqueWalletPerTransaction: 'محفظة فريدة لكل معاملة',
    eachPaymentGenerates: 'يولد كل دفع عنوان محفظة مخصص للتتبع الآلي والاحترافي.',
    fullKeyAccess: 'وصول كامل للمفاتيح',
    custodianControls: 'يتحكم الحارس بالمفاتيح الخاصة للاختبار في الوقت الفعلي ومراقبة الثغرات الأمنية.',
    completeAuditability: 'قابلية التدقيق الكاملة',
    allTransactions: 'جميع المعاملات والرسوم مرئية بشكل دائم على blockchain. بدون عمليات مخفية.',
    instantDelayAlerts: 'تنبيهات التأخير الفورية',
    realtimeDetection: 'الكشف في الوقت الفعلي عن تأخيرات الدفع أو الشذوذ على السلسلة مع إشعار تلقائي.',
    custodianPaysAllNetworkFees: 'الحارس يدفع جميع رسوم الشبكة',
    everyBlockchainCost: 'يتم تغطية كل تكلفة blockchain. يواجه العملاء رسوم دفع صفرية.',
    decentralizedTitle: 'مدفوعات لامركزية',
    decentralizedBody: 'Argon لامركزي بنسبة 100%. اقبل العملات المشفرة على السلسلة مع محافظ فريدة ومراقبة مباشرة وتسعير شفاف لكل معاملة—بدون عمولة على الحجم.',
    decentralizedCallout: 'ادفع لكل معاملة بدءاً من 50$ مقابل 500 دفعة. تكاليف الشبكة يغطيها الحارس. رؤية كاملة من الواجهة حتى التأكيد.',
    decentralizedCta: 'ابدأ',
    decentralizedCheckoutTitle: 'أكمل طلبك',
    decentralizedCheckoutProduct: 'Argon Checkout · $100.00',
    decentralizedEmailLabel: 'البريد',
    decentralizedEmailValue: 'you@company.com',
    decentralizedPayWithLabel: 'ادفع بـ',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'الشبكة',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'رسوم الشبكة مغطاة',
    decentralizedNetworkValue: '$0.00',
    decentralizedPayButton: 'ادفع $100.00',
    decentralizedSecuredBy: 'مؤمّن بواسطة Argon · تحقق على السلسلة',
    donationsTitle: 'تبرعات تبقى على السلسلة',
    donationsBody: 'اجمع تبرعات مشفرة بهدف واضح وتتبع مباشر ومحافظ فريدة لكل مساهم—شفافة من أول هدية حتى الهدف.',
    donationsCallout: 'تتبع محافظ المتبرعين في الوقت الفعلي. شاهد التقدم نحو المبلغ المستهدف مع نسبة الإنجاز في كل حملة.',
    donationsCta: 'ابدأ تبرعاً',
    donationsCardTitle: 'نظرة عامة على التبرعات',
    donationsCampaign: 'صندوق مفتوح المصدر',
    donationsCampaignMeta: '128 متبرعاً · 3 محافظ نشطة',
    donationsCampaignAmount: '$7,200',
    donationsCampaignGrowth: '↑ 72% مكتمل',
    donationsTargetLabel: 'المبلغ المستهدف',
    donationsTargetValue: '$10,000',
    donationsWalletsLabel: 'هدف هذه الحملة',
    donationsTotalLabel: 'إجمالي المُجمّع',
    donationsTotalValue: '$7,200',
    donationsTotalPercent: '72%',
    bulkTitle: 'مدفوعات جماعية على نطاق واسع',
    bulkBody: 'ادفع لعشرات المحافظ دفعة واحدة—رواتب أو موردين أو تحويلات—مع تتبع مباشر وعناوين فريدة لكل مستلم.',
    bulkCallout: 'أرسل مرة واحدة وسوِّ الكثير. راقب كل محفظة مستلم بينما تتقدم الدفعة نحو الصرف الكامل.',
    bulkCta: 'أنشئ دفعة',
    bulkCardTitle: 'نظرة عامة على الدفعة',
    bulkBatch: 'رواتب مارس',
    bulkBatchMeta: '48 من 56 أُرسلت · قيد المعالجة',
    bulkBatchAmount: '$24,800',
    bulkBatchGrowth: '↑ 86% أُرسل',
    bulkRecipientsLabel: 'المستلمون',
    bulkRecipientsValue: '56 محفظة',
    bulkRecipientsMeta: 'هدف هذه الدفعة',
    bulkTotalLabel: 'إجمالي المصروف',
    bulkTotalValue: '$24,800',
    bulkTotalPercent: '86%',
    bulkPaidLabel: 'مدفوع',
    bulkPendingLabel: 'قيد الانتظار',
    faqEyebrow: 'الدعم',
    faqTitle: 'الأسئلة الشائعة',
    faqQ1: 'هل Argon لامركزي بنسبة 100% فعلاً؟',
    faqA1: 'نعم. Argon لامركزي 100%. كل دفعة تُنشأ وتُراقب وتُتحقق على السلسلة مع محافظ فريدة ورؤية كاملة من الواجهة حتى التأكيد.',
    faqQ2: 'كيف يعمل التسعير؟',
    faqA2: 'Argon لا يأخذ عمولة على الحجم. تدفع لكل معاملة—تبدأ من 50$ مقابل 500 معاملة—مع تغطية تكاليف الشبكة وتسوية شفافة على السلسلة.',
    faqQ3: 'ما الشبكات والأصول المدعومة؟',
    faqA3: 'يدعم Argon USDC على Polygon وUSDT على BEP20 وSOL على Solana. كل دفعة تحصل على عنوان محفظة مخصص.',
    faqQ4: 'هل يمكنني تشغيل التبرعات والمدفوعات الجماعية؟',
    faqA4: 'نعم. حملات تبرع بهدف وتتبع مباشر، أو دفعات جماعية للرواتب والموردين مع حالة مدفوع / قيد الانتظار لكل محفظة.',
    faqQ5: 'من يدفع رسوم الشبكة / الغاز؟',
    faqA5: 'رسوم الشبكة يغطيها محفظة الحارس. العملاء يرسلون المبلغ بالضبط—بدون غاز مفاجئ.',
    faqQ6: 'كيف أبدأ؟',
    faqA6: 'أنشئ حساباً، احصل على مفتاح API، واستدعِ mutation Payment. من الإعداد إلى رابط الدفع خلال دقائق.',
    traditionalPayment: 'الدفع التقليدي',
    sendAmount: 'المبلغ المراد إرساله',
    processingFee: 'رسوم المعالجة (2-3%)',
    networkFee: 'رسوم الشبكة',
    recipientGets: 'المستقبل يحصل على',
    argonPayment: 'دفع أرغون',
    customerPays: 'العميل يدفع',
    custodianCoversNetworkFee: 'الحارس يغطي رسم الشبكة',
    paid: 'مدفوع',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'كيف تعمل المدفوعات الشفافة',
    transparentDesc: 'Argon لامركزي بنسبة 100%. كل دفعة مشفرة تُنشأ وتُراقب وتُتحقق على السلسلة—بدون رسوم مخفية ومع رؤية كاملة من الواجهة حتى التأكيد.',
    transparentStepOneTitle: 'مراقبة مباشرة',
    custodianMonitorsRealtime: 'يتتبع الحارس كل دفعة على السلسلة في الوقت الفعلي، فتظهر الحالة فور تحرّك التحويل.',
    transparentStepTwoTitle: 'تكاليف الشبكة مغطاة',
    allNetworkCostsCovered: 'رسوم الغاز والشبكة تُدفع من محفظة الحارس. يرسل العملاء المبلغ بالكامل—بدون خصومات مفاجئة.',
    transparentStepThreeTitle: 'وصول كامل للمفاتيح',
    fullKeyAccessForTesting: 'الوصول إلى المفاتيح الخاصة للاختبار والتحقق وفحص المحافظ وتأكيد المسارات ومراجعة كل خطوة.',
    tryArgonNow: 'جرب أرغون الآن',
    experienceZeroFeePayments: 'تجربة المدفوعات بدون رسوم بالفعل',
    paymentAmount: 'مبلغ الدفع',
    selectCryptocurrency: 'اختر العملة المشفرة',
    usdcOnPolygon: 'USDC على Polygon',
    usdtOnBep20: 'USDT على BEP20',
    totalToPay: 'الإجمالي المراد الدفع',
    proceed: 'متابعة',
    loadingPayment: 'جاري التحميل...',
    aboutThisDemo: 'حول هذا الاستعراض',
    blockchainTransparentPayments: 'مدفوعات blockchain شفافة',
    custodianPaidNetworkFees: 'رسوم الشبكة المدفوعة من قبل الحارس',
    realTimeOnChainVerification: 'التحقق في الوقت الفعلي على السلسلة',
    uniqueWallet: 'محفظة فريدة لكل معاملة',
    aboutDemoTitle: 'حول استعراض أرغون',
    demoDescription: 'يعرض هذا الاستعراض نظام الدفع الشفاف Argon. أرسل أي مبلغ بـ USDC أو USDT أو SOL بدون رسوم العملاء.',
    demoWarning: 'هذا استعراض. استخدم العملات المشفرة الاختبارية.',
    experienceEyebrow: 'على السلسلة بالتصميم',
    getStarted: 'ابدأ الآن',
    viewDocs: 'عرض المستندات',
    contact: 'اتصل',
    privacyFooter: 'الخصوصية',
    termsFooter: 'الشروط',
    checkingPayment: 'التحقق من الدفع من',
    hangOn: 'انتظر بينما نعالج دفعتك',
    paymentSuccessfulTitle: 'الدفع نجح!',
    transactionCompleted: 'تم إكمال معاملتك بنجاح.',
    amountSent: 'المبلغ المرسل',
    networkPayment: 'الشبكة',
    viewTransactionDetails: 'عرض تفاصيل المعاملة',
    closeTab: 'إغلاق التبويب',
    transactionError: 'خطأ في المعاملة',
    unableLoad: 'تعذر تحميل المعاملة:',
    cancelPaymentSuccess: 'تم إلغاء الدفع بنجاح.',
    copiedFeedback: 'تم النسخ!',
    getInTouch: 'تواصل معنا',
    contactQuestion: 'هل لديك أسئلة حول Argon؟ فريقنا هنا للمساعدة. أكمل النموذج أدناه وسنرد عليك قريباً.',
    contactOurTeam: 'اتصل بفريقنا',
    sendMessage: 'أرسل لنا رسالة وسنرد عليك في أقرب وقت ممكن',
    thankYouMessage: 'شكراً لتواصلك معنا! تم إرسال بريدك الإلكتروني. سنرد عليك قريباً.',
    fullName: 'الاسم الكامل *',
    yourName: 'اسمك',
    country: 'البلد',
    yourCountry: 'بلدك',
    emailAddress: 'عنوان البريد الإلكتروني *',
    yourEmail: 'your@email.com',
    subject: 'الموضوع *',
    aboutThis: 'ما الذي يدور حوله هذا؟',
    message: 'الرسالة *',
    tellUsMore: 'أخبرنا المزيد عن استفسارك...',
    sendMessageButton: 'إرسال الرسالة',
    fillAllFields: 'يرجى ملء جميع الحقول',
    termsTitle: 'شروط الخدمة',
    termsContent: 'سيظهر محتوى شروط وأحكام هنا.',
    privacyTitle: 'سياسة الخصوصية',
    privacyContent: 'سيظهر محتوى سياسة الخصوصية هنا.',
    aboutTitle: 'من نحن',
    cookieTitle: 'سياسة ملفات تعريف الارتباط',
    paymentSummary: 'ملخص الدفع',
    cryptocurrency: 'العملات المشفرة',
    amountToSend: 'المبلغ المراد إرساله',
    total: 'الإجمالي',
    custodianAccountAddress: 'عنوان حساب الوصي *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: 'هذا هو عنوان الحساب الذي سيتلقى المبلغ المودع. تأكد من صحة هذا العنوان قبل المتابعة، حيث سيتم إرسال الأموال إلى هذه المحفظة.',
    gasWalletPrivateKey: 'مفتاح المحفظة الخاص برسوم الغاز',
    gasKeyPlaceholder: 'أدخل المفتاح الخاص',
    gasKeyNotRequired: 'غير مطلوب لـ Solana',
    solanaNote: 'ملاحظة: هذا الحقل ليس مطلوباً لمعاملات Solana. تكون رسوم الغاز على Solana ضئيلة وسيتم التعامل معها تلقائياً.',
    securityWarning: 'تحذير الأمان: ستدفع هذه المحفظة رسوم الغاز المطلوبة لهذه المعاملة. تأكد من أن لديك رموز محلية كافية',
    toCovertransactionFees: 'لتغطية رسوم المعاملة.',
    important: 'مهم: هذا المفتاح الخاص لم يتم تخزينه على خوادمنا. لأسباب أمنية، يرجى استخدام محفظة تم إنشاؤها حديثاً. لن نكون مسؤولين عن أي مشاكل أو خسائر تواجهها نتيجة استخدام محفظة موجودة.',
    processing: 'قيد المعالجة...',
    urlParameterWarning: 'تحذير معامل URL',
    detectedInvalidParameters: 'لقد اكتشفنا بعض المعاملات غير الصحيحة في عنوان URL:',
    invalidAmount: 'مبلغ غير صحيح',
    invalidAmountMessage: 'يرجى إدخال مبلغ دفع صحيح',
    invalidAmountErrorMessage: 'يجب أن يكون المبلغ رقماً صحيحاً أكبر من 0',
    enterPositiveNumber: 'أدخل رقماً موجباً للمبلغ',
    exampleAmount: 'مثال: 100 مقابل 100 دولار أمريكي',
    decimalsAccepted: 'يتم قبول الكسور العشرية (على سبيل المثال 50.50)',
    selectAvailableNetworks: 'اختر من الشبكات المتاحة: USDC (Polygon) أو USDT (BSC) أو SOL (Solana)',
    eachNetworkSupports: 'تدعم كل شبكة عملات مشفرة مختلفة',
    goBackAndFix: 'العودة والإصلاح',
    footerArgonDesc: 'مدفوعات مشفرة لامركزية 100%. شفافة على البلوكتشين. مراقبة من الحارس. تسعير لكل معاملة—بدون عمولة.',
    footerResources: 'الموارد',
    footerFeatures: 'الميزات',
    footerFeaturesLink: 'الميزات',
    footerPricingLink: 'التسعير',
    footerFaqLink: 'الأسئلة',
    footerCompany: 'الشركة',
    footerCommunity: 'المجتمع',
    footerLegal: 'قانوني',
    footerGithub: 'GitHub',
    footerDocumentation: 'توثيق',
    footerApiDocs: 'مستندات API',
    footerTelegram: 'Telegram',
    footerSupport: 'الدعم',
    footerFeedback: 'التعليق',
    footerTerms: 'الشروط',
    footerPrivacy: 'الخصوصية',
    footerAbout: 'من نحن',
    footerCookies: 'ملفات تعريف الارتباط',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'تحذير',
    warningDefaultMessage: 'يرجى مراجعة ما يلي:',
  },
  ru: {
    loading: 'Загрузка деталей транзакции...',
    youWillSend: 'Вы отправите',
    selectBlockchain: 'Выберите блокчейн',
    pay: 'Оплатить',
    cancelPayment: 'Отменить платеж',
    terms: 'Условия использования',
    privacyPolicy: 'Политика конфиденциальности',
    byConnecting: 'Подключаясь к платформе, вы соглашаетесь с нашими',
    and: 'и',
    scanQr: 'Отсканируйте QR-код или скопируйте адрес кошелька для совершения платежа',
    expiresIn: 'Истекает через',
    minutes: 'минут',
    imadeMadePayment: 'Я произвел платеж',
    processingPayment: 'Обработка платежа...',
    paymentSuccessful: 'Платеж прошел успешно',
    yourPayment: 'Ваш платеж от',
    hasBeenSubmitted: 'успешно отправлен',
    transactionId: 'ID транзакции',
    amount: 'Сумма',
    status: 'Статус',
    pendingVerification: 'Ожидание проверки',
    viewTransaction: 'Просмотреть транзакцию',
    equivalentTo: '~ эквивалентно',
    selectLanguage: 'Выберите предпочтительный язык',
    chooseLanguage: 'Выберите язык для начала',
    backToHome: 'Вернуться на главную',
    transactions: 'Транзакции',
    network: 'Сеть',
    walletAddress: 'Адрес кошелька',
    blockchainTransparency: 'Прозрачность Blockchain.',
    realTimeVerification: 'Децентрализованные платежи.',
    everyTransaction: 'Argon на 100% децентрализован. Каждая транзакция отслеживается в блокчейне хранилищем. Все сетевые сборы покрыты. Уникальный кошелек для каждой транзакции. Полный доступ к ключам для тестирования. Полная прозрачность.',
    customerFees: 'Комиссии клиентов',
    onChain: 'На цепи',
    monitoring: 'Мониторинг',
    liveMonitoring: 'Мониторинг в реальном времени',
    heroPartnersTagline: 'Обеспечиваем on-chain платежи для ведущих продуктов',
    integrateTitle: 'Принимайте криптоплатежи с Argon—без процентной комиссии, запуск за минуты.',
    integrateSubtitle: 'Подключите Argon через простой API. Argon на 100% децентрализован—платите за транзакцию, а не процент с каждого платежа. От $50 за 500 транзакций, сетевые расходы покрывает хранитель.',
    integrateTabBuild: 'Настройка',
    integrateTabAccept: 'Оплата',
    integrateTabSettle: 'Отслеживание',
    integrateTabBuildShort: 'API',
    integrateTabAcceptShort: 'Оплата',
    integrateTabSettleShort: 'Статус',
    integratePanelTitle: 'Портал разработчика',
    integrateZeroFees: 'Без комиссии %',
    integrateZeroFeesDesc: 'Оплата за транзакцию от $50 / 500 txn. Хранитель покрывает сетевые расходы.',
    integrateApiReady: 'Один API',
    integrateApiReadyDesc: 'Подключите Argon и быстро принимайте on-chain платежи.',
    integrateLiveStatus: 'Онлайн',
    payNow: 'Оплатить сейчас',
    usdCoin: 'Монета USD',
    solana: 'Solana',
    featuresEyebrow: 'Всё on-chain',
    completeBlockchainTransparency: 'Полная прозрачность блокчейна',
    realTimeOnChain: 'Argon на 100% децентрализован. Мониторинг в реальном времени в цепи. Сборы оплачены хранилищем. Полный доступ к ключам. Без скрытых процессов.',
    gapEyebrow: 'ПОЧЕМУ ARGON',
    gapHeadline: 'Другие крипто-шлюзы берут процент. Argon тарифицирует по транзакциям.',
    gapBodyOne: 'Большинство криптовалютных checkout-платформ всё ещё работают как посредники. Coinbase Commerce, BitPay и NOWPayments принимают цифровые активы — но расчёты часто включают процентные комиссии, наценки, неожиданный gas и слабую прозрачность хранения. Основатели собирают API, эксплорер и дашборд, чтобы понять, прошёл ли перевод USDC или USDT.',
    gapBodyTwoBefore: 'Стек с процентной комиссией съедает маржу по мере роста. ',
    gapBodyTwoHighlight: 'Argon устроен иначе:',
    gapBodyTwoAfter: ' 100% децентрализация, без комиссии с оборота—прозрачная цена за транзакцию от $50 за 500 транзакций, один GraphQL API, сетевые расходы покрывает хранитель, уникальный кошелёк на платёж и живой мониторинг в одном дашборде.',
    realTimeMonitoring: 'Мониторинг в реальном времени',
    everyTransactionTracked: 'Каждая транзакция отслеживается и проверяется мгновенно в блокчейне хранилищем.',
    custodianPaidFees: 'Сборы, оплаченные хранилищем',
    allNetworkFeeCovered: 'Все сетевые сборы покрыты кошельком хранилища. Клиенты не платят никаких комиссий блокчейна.',
    uniqueWalletPerTransaction: 'Уникальный кошелек на транзакцию',
    eachPaymentGenerates: 'Каждый платеж генерирует выделенный адрес кошелька для автоматизированного профессионального отслеживания.',
    fullKeyAccess: 'Полный доступ к ключам',
    custodianControls: 'Хранилище контролирует приватные ключи для тестирования в реальном времени и наблюдения за уязвимостями.',
    completeAuditability: 'Полная проверяемость',
    allTransactions: 'Все транзакции и сборы постоянно видны в блокчейне. Без скрытых процессов.',
    instantDelayAlerts: 'Мгновенные предупреждения о задержке',
    realtimeDetection: 'Обнаружение в реальном времени задержек платежей или аномалий в цепи с автоматическим уведомлением.',
    custodianPaysAllNetworkFees: 'Хранилище платит все сетевые сборы',
    everyBlockchainCost: 'Каждая стоимость блокчейна покрыта. Клиенты испытывают нулевые комиссии платежа.',
    decentralizedTitle: 'Децентрализованные платежи',
    decentralizedBody: 'Argon на 100% децентрализован. Принимайте крипто on-chain с уникальными кошельками, живым мониторингом и прозрачной ценой за транзакцию—без комиссии с оборота.',
    decentralizedCallout: 'Оплата за транзакцию от $50 за 500 платежей. Сетевые расходы покрывает хранитель. Полная видимость от API до подтверждения.',
    decentralizedCta: 'Начать',
    decentralizedCheckoutTitle: 'Завершите заказ',
    decentralizedCheckoutProduct: 'Argon Checkout · $100.00',
    decentralizedEmailLabel: 'Email',
    decentralizedEmailValue: 'you@company.com',
    decentralizedPayWithLabel: 'Оплатить',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'Сеть',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'Сетевой сбор покрыт',
    decentralizedNetworkValue: '$0.00',
    decentralizedPayButton: 'Оплатить $100.00',
    decentralizedSecuredBy: 'Защищено Argon · On-chain проверка',
    donationsTitle: 'Пожертвования, которые остаются on-chain',
    donationsBody: 'Собирайте крипто-пожертвования с ясной целью, живым прогрессом и уникальными кошельками для каждого донора—прозрачно от первого взноса до цели.',
    donationsCallout: 'Отслеживайте кошельки доноров в реальном времени. Видьте прогресс к целевой сумме с процентом выполнения в каждой кампании.',
    donationsCta: 'Начать сбор',
    donationsCardTitle: 'Обзор пожертвований',
    donationsCampaign: 'Open Source Fund',
    donationsCampaignMeta: '128 доноров · 3 активных кошелька',
    donationsCampaignAmount: '$7,200',
    donationsCampaignGrowth: '↑ 72% выполнено',
    donationsTargetLabel: 'Целевая сумма',
    donationsTargetValue: '$10,000',
    donationsWalletsLabel: 'Цель кампании',
    donationsTotalLabel: 'Всего собрано',
    donationsTotalValue: '$7,200',
    donationsTotalPercent: '72%',
    bulkTitle: 'Массовые выплаты в масштабе',
    bulkBody: 'Платите десяткам кошельков одним батчем—зарплата, поставщики или выплаты—с живым прогрессом и уникальным адресом для каждого получателя.',
    bulkCallout: 'Отправьте один раз — рассчитайтесь со многими. Отслеживайте каждый кошелёк получателя по мере выполнения батча.',
    bulkCta: 'Создать батч',
    bulkCardTitle: 'Обзор батча',
    bulkBatch: 'Зарплата за март',
    bulkBatchMeta: '48 из 56 отправлено · в процессе',
    bulkBatchAmount: '$24,800',
    bulkBatchGrowth: '↑ 86% отправлено',
    bulkRecipientsLabel: 'Получатели',
    bulkRecipientsValue: '56 кошельков',
    bulkRecipientsMeta: 'Цель этого батча',
    bulkTotalLabel: 'Всего выплачено',
    bulkTotalValue: '$24,800',
    bulkTotalPercent: '86%',
    bulkPaidLabel: 'Оплачено',
    bulkPendingLabel: 'Ожидает',
    faqEyebrow: 'Поддержка',
    faqTitle: 'Частые вопросы',
    faqQ1: 'Argon действительно на 100% децентрализован?',
    faqA1: 'Да. Argon на 100% децентрализован. Каждый платёж создаётся, отслеживается и проверяется on-chain с уникальными кошельками и полной видимостью от API до подтверждения.',
    faqQ2: 'Как устроено ценообразование?',
    faqA2: 'Argon не берёт комиссию с оборота. Вы платите за транзакцию—от $50 за 500 транзакций—с покрытием сетевых расходов и прозрачным on-chain расчётом.',
    faqQ3: 'Какие сети и активы поддерживаются?',
    faqA3: 'Argon поддерживает USDC на Polygon, USDT на BEP20 и SOL на Solana. Каждый платёж получает отдельный адрес кошелька.',
    faqQ4: 'Можно ли запускать донаты и массовые выплаты?',
    faqA4: 'Да. Кампании донатов с целью и прогрессом, или батчи для зарплаты и поставщиков со статусом оплачено / ожидает по каждому кошельку.',
    faqQ5: 'Кто платит сетевые / gas-комиссии?',
    faqA5: 'Сетевые комиссии покрывает кошелёк хранителя. Клиенты отправляют точную сумму—без неожиданного gas.',
    faqQ6: 'Как начать?',
    faqA6: 'Создайте аккаунт, получите API-ключ и вызовите мутацию Payment. От настройки до ссылки на checkout за минуты.',
    traditionalPayment: 'Традиционный платеж',
    sendAmount: 'Сумма для отправки',
    processingFee: 'Комиссия обработки (2-3%)',
    networkFee: 'Сетевой сбор',
    recipientGets: 'Получатель получает',
    argonPayment: 'Платеж Argon',
    customerPays: 'Клиент платит',
    custodianCoversNetworkFee: 'Хранилище покрывает сетевой сбор',
    paid: 'Оплачено',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'Как работают прозрачные платежи',
    transparentDesc: 'Argon на 100% децентрализован. Каждый криптоплатёж создаётся, отслеживается и проверяется on-chain—без скрытых комиссий и с полной видимостью от API до подтверждения.',
    transparentStepOneTitle: 'Живой мониторинг',
    custodianMonitorsRealtime: 'Хранитель отслеживает каждый платёж on-chain в реальном времени, поэтому статус виден сразу, как только перевод движется.',
    transparentStepTwoTitle: 'Сетевые расходы покрыты',
    allNetworkCostsCovered: 'Gas и сетевые комиссии оплачивает кошелёк хранителя. Клиенты отправляют точную сумму—без неожиданных удержаний.',
    transparentStepThreeTitle: 'Полный доступ к ключам',
    fullKeyAccessForTesting: 'Доступ к приватным ключам для тестов и проверки: инспектируйте кошельки, подтверждайте потоки и аудируйте каждый шаг.',
    tryArgonNow: 'Попробуйте Argon сейчас',
    experienceZeroFeePayments: 'Опыт платежей без комиссий в действии',
    paymentAmount: 'Сумма платежа',
    selectCryptocurrency: 'Выберите криптовалюту',
    usdcOnPolygon: 'USDC на Polygon',
    usdtOnBep20: 'USDT на BEP20',
    totalToPay: 'Всего к оплате',
    proceed: 'Продолжить',
    loadingPayment: 'Загрузка...',
    aboutThisDemo: 'Об этой демонстрации',
    blockchainTransparentPayments: 'Прозрачные платежи блокчейна',
    custodianPaidNetworkFees: 'Сетевые сборы, оплаченные хранилищем',
    realTimeOnChainVerification: 'Проверка в реальном времени в цепи',
    uniqueWallet: 'Уникальный кошелек на транзакцию',
    aboutDemoTitle: 'Об демонстрации Argon',
    demoDescription: 'Эта демонстрация показывает систему прозрачных платежей Argon. Отправляйте любую сумму в USDC, USDT или SOL без комиссий клиентов.',
    demoWarning: 'Это демонстрация. Используйте тестовые криптовалюты.',
    experienceEyebrow: 'On-chain по замыслу',
    getStarted: 'Начать',
    viewDocs: 'Документация',
    contact: 'Контакт',
    privacyFooter: 'Конфиденциальность',
    termsFooter: 'Условия',
    checkingPayment: 'Проверка платежа',
    hangOn: 'Подождите, пока мы обработаем ваш платеж',
    paymentSuccessfulTitle: 'Платеж успешен!',
    transactionCompleted: 'Ваша транзакция успешно завершена.',
    amountSent: 'Отправленная Сумма',
    networkPayment: 'Сеть',
    viewTransactionDetails: 'Просмотреть детали транзакции',
    closeTab: 'Закрыть вкладку',
    transactionError: 'Ошибка транзакции',
    unableLoad: 'Не удалось загрузить транзакцию:',
    cancelPaymentSuccess: 'Платеж успешно отменен.',
    copiedFeedback: 'Скопировано!',
    getInTouch: 'Свяжитесь с нами',
    contactQuestion: 'У вас есть вопросы об Argon? Наша команда здесь для помощи. Заполните форму ниже, и мы ответим вам вскоре.',
    contactOurTeam: 'Свяжитесь с нашей командой',
    sendMessage: 'Отправьте нам сообщение, и мы ответим как можно скорее',
    thankYouMessage: 'Спасибо, что связались с нами! Ваше письмо отправлено. Мы свяжемся с вами вскоре.',
    fullName: 'Полное имя *',
    yourName: 'Ваше имя',
    country: 'Страна',
    yourCountry: 'Ваша страна',
    emailAddress: 'Адрес электронной почты *',
    yourEmail: 'ваш@email.com',
    subject: 'Тема *',
    aboutThis: 'О чем это?',
    message: 'Сообщение *',
    tellUsMore: 'Расскажите нам подробнее о вашем вопросе...',
    sendMessageButton: 'Отправить сообщение',
    fillAllFields: 'Пожалуйста, заполните все поля',
    termsTitle: 'Условия обслуживания',
    termsContent: 'Содержание условий использования будет отображаться здесь.',
    privacyTitle: 'Политика конфиденциальности',
    privacyContent: 'Содержание политики конфиденциальности будет отображаться здесь.',
    aboutTitle: 'О нас',
    cookieTitle: 'Политика файлов cookie',
    paymentSummary: 'Сводка платежа',
    cryptocurrency: 'Криптовалюта',
    amountToSend: 'Сумма к отправке',
    total: 'Всего',
    custodianAccountAddress: 'Адрес счета хранителя *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: 'Это адрес счета, который получит депонированную сумму. Убедитесь, что этот адрес верен перед продолжением, так как средства будут отправлены в этот кошелек.',
    gasWalletPrivateKey: 'Закрытый ключ кошелька газовых сборов',
    gasKeyPlaceholder: 'Введите закрытый ключ',
    gasKeyNotRequired: 'Не требуется для Solana',
    solanaNote: 'Примечание: это поле не требуется для транзакций Solana. Сетевые сборы на Solana минимальны и будут обработаны автоматически.',
    securityWarning: 'Предупреждение о безопасности: этот кошелек будет платить комиссии за газ, необходимые для этой транзакции. Убедитесь, что у вас достаточно собственных токенов',
    toCovertransactionFees: 'для покрытия комиссий за транзакцию.',
    important: 'Важно: этот закрытый ключ НЕ хранится на наших серверах. В целях безопасности используйте вновь созданный кошелек. Мы не несем ответственность за любые проблемы или убытки, которые вы можете испытать при использовании существующего кошелька.',
    processing: 'Обработка...',
    urlParameterWarning: 'Предупреждение параметра URL',
    detectedInvalidParameters: 'Мы обнаружили некоторые недействительные параметры в URL:',
    invalidAmount: 'Неверная сумма',
    invalidAmountMessage: 'Пожалуйста, введите корректную сумму платежа',
    invalidAmountErrorMessage: 'Сумма должна быть действительным числом больше 0',
    enterPositiveNumber: 'Введите положительное число для суммы',
    exampleAmount: 'Пример: 100 для 100 USD',
    decimalsAccepted: 'Допускаются десятичные числа (например 50,50)',
    selectAvailableNetworks: 'Выберите из доступных сетей: USDC (Polygon), USDT (BSC) или SOL (Solana)',
    eachNetworkSupports: 'Каждая сеть поддерживает разные криптовалюты',
    goBackAndFix: 'Вернуться и исправить',
    footerArgonDesc: '100% децентрализованные криптоплатежи. Прозрачные on-chain. Контроль хранителя. Оплата за транзакцию—без процентной комиссии.',
    footerResources: 'Ресурсы',
    footerFeatures: 'Возможности',
    footerFeaturesLink: 'Возможности',
    footerPricingLink: 'Цены',
    footerFaqLink: 'FAQ',
    footerCompany: 'Компания',
    footerCommunity: 'Сообщество',
    footerLegal: 'Юридический',
    footerGithub: 'GitHub',
    footerDocumentation: 'Документация',
    footerApiDocs: 'Документы API',
    footerTelegram: 'Telegram',
    footerSupport: 'Поддержка',
    footerFeedback: 'Обратная связь',
    footerTerms: 'Условия',
    footerPrivacy: 'Конфиденциальность',
    footerAbout: 'О нас',
    footerCookies: 'Cookies',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'Предупреждение',
    warningDefaultMessage: 'Пожалуйста, проверьте следующее:',
  },
  ig: {
    loading: 'Ilooding ọmụmụ ngbanwe...',
    youWillSend: 'I ga-eziga',
    selectBlockchain: 'Horo Blockchain',
    pay: 'Gba ụgwọ',
    cancelPayment: 'Kapu Ụgwọ',
    terms: 'Usoro Ọrụ',
    privacyPolicy: 'Nzubahụ Nkporo Ozi',
    byConnecting: 'N\'ịjikọ na ihe nkiri, ị na-anzere nnukwu',
    and: 'na',
    scanQr: 'Scanụ QR code ma ọ bụ detuo adreesị wallet iji mee ụgwọ',
    expiresIn: 'Agbapụtụ n\'ime',
    minutes: 'nkeji',
    imadeMadePayment: 'Emere m ụgwọ',
    processingPayment: 'Na-ụkwụ ụgwọ...',
    paymentSuccessful: 'Ụgwọ ruru nka',
    yourPayment: 'Ụgwọ gị nke',
    hasBeenSubmitted: 'ezubela nke ọma',
    transactionId: 'ID Ngbanwe',
    amount: 'Oke',
    status: 'Ọnọdụ',
    pendingVerification: 'Na-achere Ntụze',
    viewTransaction: 'Legha Ngbanwe',
    equivalentTo: '~ nha ya',
    selectLanguage: 'Horo Asụsụ Gị Kacha Mma',
    chooseLanguage: 'Horo asụsụ iji malite',
    backToHome: 'Laghachi na mmalite',
    transactions: 'Ngbanwe',
    network: 'Netwọkụ',
    walletAddress: 'Adreesị Wallet',
    blockchainTransparency: 'Iko blockchain.',
    realTimeVerification: 'Ụgwọ Decentralized.',
    everyTransaction: 'Argon bụ 100% decentralized. A na-elekọta ọkọ ọ bụla n\'iti blockchain site na onye nlekọta. Agbụ netwọk niile e mebeela. Wallet pụrụ iche maka ọkọ ọ bụla. Ohere zuru oke maka nyocha. Enweghị ihe ezoro ezo.',
    customerFees: 'Ụgwọ ndị ahịa',
    onChain: 'N\'iti chi',
    monitoring: 'Nlekọta',
    liveMonitoring: 'Nlekọta oge n\'oge',
    heroPartnersTagline: 'Na-akwado ịkwụ ụgwọ on-chain n\'ofe ngwaahịa kachasị mkpa',
    integrateTitle: 'Nabata ịkwụ ụgwọ crypto na Argon—enweghị commission, na-arụ ọrụ n\'ime nkeji ole na ole.',
    integrateSubtitle: 'Tinye Argon site na API dị mfe. Argon bụ 100% decentralized—kwụọ ụgwọ maka ọkọ ọ bụla, ọ bụghị pasentị n\'ụgwọ ọ bụla. Malite na $50 maka ọkọ 500, ebe onye nlekọta na-ekpuchi ụgwọ netwọk.',
    integrateTabBuild: 'Nhazi',
    integrateTabAccept: 'Checkout',
    integrateTabSettle: 'Nlekọta',
    integrateTabBuildShort: 'Nhazi',
    integrateTabAcceptShort: 'Kwụọ',
    integrateTabSettleShort: 'Lee',
    integratePanelTitle: 'Ọnụ ụzọ mmepe',
    integrateZeroFees: 'Enweghị commission',
    integrateZeroFeesDesc: 'Ọnụahịa maka ọkọ site na $50 / 500 txn. Onye nlekọta na-ekpuchi ụgwọ netwọk.',
    integrateApiReady: 'Otu API',
    integrateApiReadyDesc: 'Tinye Argon ma malite ịnabata ịkwụ ụgwọ on-chain ngwa ngwa.',
    integrateLiveStatus: 'Dị ndụ',
    payNow: 'Gba ụgwọ ugbu a',
    usdCoin: 'USD Coin',
    solana: 'Solana',
    featuresEyebrow: 'Ihe niile on-chain',
    completeBlockchainTransparency: 'Iko Blockchain Zuru Oke',
    realTimeOnChain: 'Argon bụ 100% decentralized. Nlekọta oge n\'oge n\'iti chi. Ụgwọ e mebeela site na onye nlekọta. Ohere zuru oke maka mkpọ. Enweghị usoro ezoro ezo.',
    gapEyebrow: 'GỊNỊ MERE ARGON',
    gapHeadline: 'Ọnụ ụzọ crypto ndị ọzọ na-ewere commission. Argon na-ana ụgwọ maka ọkọ ọ bụla.',
    gapBodyOne: 'Ọtụtụ platform checkout crypto ka na-eme dị ka ndị etiti. Coinbase Commerce, BitPay, na NOWPayments nwere ike ịnabata akụ dijitalụ—mana nkwụnye ụgwọ na-agụnyekarị commission pasentị, mmụba, ụgwọ gas na-atụghị anya, na ohere ole na ole maka nchekwa. Ndị nwe ụlọ ọrụ na-ejikọta API, explorer, na dashboard nanị iji mara ma USDC ma ọ bụ USDT agafeela.',
    gapBodyTwoBefore: 'Usoro nwere commission na-eri uru gị ka ị na-eto. ',
    gapBodyTwoHighlight: 'Argon dị iche:',
    gapBodyTwoAfter: ' 100% decentralized, enweghị commission n\'olu ịkwụ ụgwọ—ọnụahịa doro anya maka ọkọ ọ bụla site na $50 maka ọkọ 500, otu GraphQL API, ụgwọ netwọk onye nlekọta na-ekpuchi, wallet pụrụ iche, na nlekọta blockchain dị ndụ n\'otu dashboard.',
    realTimeMonitoring: 'Nlekọta Oge N\'oge',
    everyTransactionTracked: 'A na-achọ ogbugbụ ọkọ nile ma na-agba uche n\'ụlọ blockchain oge n\'oge site na onye na-edobe.',
    custodianPaidFees: 'Ụgwọ e mebeela site na onye na-edobe',
    allNetworkFeeCovered: 'Agbụ netwọk niile e mebeela site na wallet onye na-edobe. Ndị ahịa agbụ blockchain ọkụkụ.',
    uniqueWalletPerTransaction: 'Wallet Pụrụ iche Maka Ọkọ Ọkọ',
    eachPaymentGenerates: 'Ụgwọ ọkọ nile na-enwe adreesị wallet pụrụ iche maka nlekọta otomatik na ọfụ.',
    fullKeyAccess: 'Ohere Zuru Oke Maka Mkpọ',
    custodianControls: 'Onye na-edobe na-achịkwa ọkpụ na-akpakwa maka nyocha oge n\'oge na nlekọta njehie.',
    completeAuditability: 'Ihe ọkụkụ Zuru Oke',
    allTransactions: 'Ogbugbụ ọkọ nile na agbụ pụtara anya n\'ebe ebee n\'iti chi. Emepụ emepụ ihe ọkụkụ.',
    instantDelayAlerts: 'Aba Mmalite Ntughari N\'oge N\'oge',
    realtimeDetection: 'Nchọpụta oge n\'oge nke ntughari ụgwọ ma ọ bụ ihe ndị ọzọ n\'iti chi nwere aba otomatik.',
    custodianPaysAllNetworkFees: 'Onye na-edobe na-agba ụgwọ agbụ netwọk niile',
    everyBlockchainCost: 'Agbụ blockchain nile e mebeela. Ndị ahịa nwere agbụ ụgwọ ihe ọkụkụ.',
    decentralizedTitle: 'Ụgwọ Decentralized',
    decentralizedBody: 'Argon bụ 100% Decentralized. Nabata crypto on-chain site na wallet pụrụ iche, nlekọta dị ndụ, na ọnụahịa doro anya maka ọkọ—enweghị commission n\'olu.',
    decentralizedCallout: 'Kwụọ ụgwọ maka ọkọ site na $50 maka ọkọ 500. Ụgwọ netwọk onye nlekọta na-ekpuchi. Ohere zuru oke site na API ruo nkwenye.',
    decentralizedCta: 'Bido',
    decentralizedCheckoutTitle: 'Mechaa ozi gị',
    decentralizedCheckoutProduct: 'Argon Checkout · $100.00',
    decentralizedEmailLabel: 'Email',
    decentralizedEmailValue: 'you@company.com',
    decentralizedPayWithLabel: 'Kwụọ site na',
    decentralizedPayWithValue: 'USDC',
    decentralizedSettleLabel: 'Netwọk',
    decentralizedSettleValue: 'Polygon',
    decentralizedNetworkLabel: 'Ụgwọ netwọk e kpuchiri',
    decentralizedNetworkValue: '$0.00',
    decentralizedPayButton: 'Kwụọ $100.00',
    decentralizedSecuredBy: 'Nchekwa Argon · Nkwado on-chain',
    donationsTitle: 'Onyinye na-anọ on-chain',
    donationsBody: 'Nakọta onyinye crypto nwere ebumnuche doro anya, nlekọta ọganihu dị ndụ, na wallet pụrụ iche maka onye ọ bụla—iko site na onyinye mbụ ruo ebumnuche.',
    donationsCallout: 'Soro wallet ndị nyere onyinye oge n\'oge. Hụ ọganihu gaa n\'ego ebumnuche na pasentị mezuru n\'ime mkpọsa ọ bụla.',
    donationsCta: 'Malite onyinye',
    donationsCardTitle: 'Nchịkọta onyinye',
    donationsCampaign: 'Open Source Fund',
    donationsCampaignMeta: '128 ndị nyere · wallet 3 dị ndụ',
    donationsCampaignAmount: '$7,200',
    donationsCampaignGrowth: '↑ 72% mezuru',
    donationsTargetLabel: 'Ego ebumnuche',
    donationsTargetValue: '$10,000',
    donationsWalletsLabel: 'Ebumnuche mkpọsa a',
    donationsTotalLabel: 'Ngụkọ e wetara',
    donationsTotalValue: '$7,200',
    donationsTotalPercent: '72%',
    bulkTitle: 'Ụgwọ bulk n\'ogo',
    bulkBody: 'Kwụọ ọtụtụ wallet n\'otu batch—ụgwọ ọrụ, ndị na-ere, ma ọ bụ payout—na nlekọta dị ndụ na adreesị pụrụ iche maka onye ọ bụla.',
    bulkCallout: 'Zipu otu ugboro, kwụọ ọtụtụ. Soro wallet onye ọ bụla ka batch na-aga n\'ihu.',
    bulkCta: 'Mepụta batch',
    bulkCardTitle: 'Nchịkọta batch',
    bulkBatch: 'Ụgwọ ọrụ March',
    bulkBatchMeta: '48 n\'ime 56 e zipụrụ · na-arụ ọrụ',
    bulkBatchAmount: '$24,800',
    bulkBatchGrowth: '↑ 86% e zipụrụ',
    bulkRecipientsLabel: 'Ndị nnata',
    bulkRecipientsValue: 'wallet 56',
    bulkRecipientsMeta: 'Ebumnuche batch a',
    bulkTotalLabel: 'Ngụkọ e kwụrụ',
    bulkTotalValue: '$24,800',
    bulkTotalPercent: '86%',
    bulkPaidLabel: 'Akwụọla',
    bulkPendingLabel: 'Na-eche',
    faqEyebrow: 'Nkwado',
    faqTitle: 'Ajụjụ a na-ajụkarị',
    faqQ1: 'Argon ọ bụ ezie 100% decentralized?',
    faqA1: 'Ee. Argon bụ 100% decentralized. A na-emepụta, na-elekọta, ma na-agba nkwado ụgwọ ọ bụla on-chain site na wallet pụrụ iche na ohere zuru oke site na API ruo nkwenye.',
    faqQ2: 'Olee otú ọnụahịa si arụ ọrụ?',
    faqA2: 'Argon anaghị ewere commission n\'olu. Ị na-akwụ ụgwọ maka ọkọ—malite na $50 maka ọkọ 500—na ụgwọ netwọk e kpuchiri na nkwụnye on-chain doro anya.',
    faqQ3: 'Kedu netwọk na akụ a na-akwado?',
    faqA3: 'Argon na-akwado USDC na Polygon, USDT na BEP20, na SOL na Solana. Ụgwọ ọ bụla na-enweta adreesị wallet pụrụ iche.',
    faqQ4: 'Enwere m ike ịme onyinye na ụgwọ bulk?',
    faqA4: 'Ee. Mkpọsa onyinye nwere ebumnuche na ọganihu, ma ọ bụ batch maka ụgwọ ọrụ na ndị na-ere nwere ọnọdụ akwụọla / na-eche maka wallet ọ bụla.',
    faqQ5: 'Onye na-akwụ ụgwọ netwọk / gas?',
    faqA5: 'Ụgwọ netwọk wallet onye nlekọta na-ekpuchi. Ndị ahịa na-eziga ego zuru ezu—enweghị gas ihe ịtụnanya.',
    faqQ6: 'Olee otú m ga-esi malite?',
    faqA6: 'Mepụta akaụntụ, nweta API key gị, kpọọ Payment mutation. Site na nhazi ruo njikọ checkout n\'ime nkeji ole na ole.',
    traditionalPayment: 'Ụgwọ Gara aga',
    sendAmount: 'Nsoghara Izipu',
    processingFee: 'Ụgwọ Ọrụ (2-3%)',
    networkFee: 'Agbụ Netwọk',
    recipientGets: 'Onye natara na-enweta',
    argonPayment: 'Ụgwọ Argon',
    customerPays: 'Onye azụ na-agba ụgwọ',
    custodianCoversNetworkFee: 'Onye na-edobe na-akpụ agbụ netwọk',
    paid: 'E gbaara ụgwọ',
    transparentEyebrow: 'On-chain by design',
    howTransparentPaymentsWork: 'Otu ụgwọ Iko na-arụ ọrụ',
    transparentDesc: 'Argon bụ 100% decentralized. Ụgwọ crypto ọ bụla a na-emepụta, na-elekọta, ma na-agba nkwado on-chain—enweghị ụgwọ ezoro ezo na ohere zuru oke site na API ruo nkwenye.',
    transparentStepOneTitle: 'Nlekọta dị ndụ',
    custodianMonitorsRealtime: 'Onye nlekọta na-eso ụgwọ ọ bụla on-chain oge n\'oge, ka ọnọdụ wee pụta ozugbo ntụgharị malitere.',
    transparentStepTwoTitle: 'Ụgwọ netwọk e kpuchiri',
    allNetworkCostsCovered: 'Gas na ụgwọ netwọk a na-akwụ site na wallet onye nlekọta. Ndị ahịa na-eziga ego zuru ezu—enweghị mwepụ ihe ịtụnanya.',
    transparentStepThreeTitle: 'Ohere zuru oke maka mkpọ',
    fullKeyAccessForTesting: 'Nweta mkpọ nzuzo maka nyocha na nkwado ka ị nwee ike ilele wallet, kwado usoro, ma nyochaa nzọụkwụ ọ bụla.',
    tryArgonNow: 'Nwaa Argon ugbu a',
    experienceZeroFeePayments: 'Ahụ ụgwọ ihe ọkụkụ n\'ime ihe',
    paymentAmount: 'Nsoghara Ụgwọ',
    selectCryptocurrency: 'Horo Crypto-ego',
    usdcOnPolygon: 'USDC na Polygon',
    usdtOnBep20: 'USDT na BEP20',
    totalToPay: 'Ngụkọ Zuru Oke',
    proceed: 'Gaa n\'ihu',
    loadingPayment: 'Ilooding...',
    aboutThisDemo: 'Banyere nke a Demo',
    blockchainTransparentPayments: 'Ụgwọ iko blockchain',
    custodianPaidNetworkFees: 'Agbụ netwọk e gbaara ụgwọ site na onye na-edobe',
    realTimeOnChainVerification: 'Nkwado oge n\'oge n\'iti chi',
    uniqueWallet: 'Wallet pụrụ iche maka ọkọ ọkọ',
    aboutDemoTitle: 'Banyere Argon Demo',
    demoDescription: 'Demo a na-egosi usoro ụgwọ iko Argon. Izipu ego ọkọ n\'USDC, USDT ma ọ bụ SOL na-enweghị ụgwọ ndị ahịa.',
    demoWarning: 'Nke a bụ ngosi. Jiri crypto testnet.',
    experienceEyebrow: 'On-chain site na nhazi',
    getStarted: 'Bido',
    viewDocs: 'Lelee akwụkwọ',
    contact: 'Kpọtụ',
    privacyFooter: 'Nkporo ozi',
    termsFooter: 'Usoro',
    checkingPayment: 'Nlekọta Ụgwọ nke',
    hangOn: 'Chere ka ọ bụrụ na anyị na-ụkwụ gị ụgwọ',
    paymentSuccessfulTitle: 'Ụgwọ ruru nka!',
    transactionCompleted: 'Ngbanwe gị akmaliteela nke ọma.',
    amountSent: 'Oke Ezigara',
    networkPayment: 'Netwọkụ',
    viewTransactionDetails: 'Legha ihe ngbanwe',
    closeTab: 'Melee Tabu',
    transactionError: 'Njehie Ngbanwe',
    unableLoad: 'Enweghị ike iloodu ngbanwe:',
    cancelPaymentSuccess: 'Ụgwọ kaputala nke ọma.',
    copiedFeedback: 'E deturu!',
    getInTouch: 'Kpọtụ Anyị',
    contactQuestion: 'Ịnụ ajụjụ banyere Argon? Ụmụ ọrụ anyị nọ ebe a iji nyere gị aka. Jepụta nhazụ n\'aha a na anyị ga-azaghara gị ngwa ngwa.',
    contactOurTeam: 'Kpọtụ Ụmụ ọrụ Anyị',
    sendMessage: 'Zigara ụ ozi na anyị ga-aza ngwa ngwa ka ọ dịkwa mma',
    thankYouMessage: 'Daalụ maka ikpọtụ! E zigaala mejụ gị. Anyị ga-azaghara gị ngwa ngwa.',
    fullName: 'Aha Zuru Oke *',
    yourName: 'Aha gị',
    country: 'Mba',
    yourCountry: 'Mba gị',
    emailAddress: 'Adreesị mejụ *',
    yourEmail: 'gị@email.com',
    subject: 'Isiokwu *',
    aboutThis: 'Gini ka nke a bụ?',
    message: 'Ozi *',
    tellUsMore: 'Kọwa ọtụtụ mma banyere ajụjụ gị...',
    sendMessageButton: 'Zigara Ozi',
    fillAllFields: 'Jiri isi pụta ogwe niile',
    termsTitle: 'Usoro Ọrụ',
    termsContent: 'Ọdịnaya nke usoro na ụkpụkpụ ga-apụta ebe a.',
    privacyTitle: 'Nzubahụ Nkporo Ozi',
    privacyContent: 'Ọdịnaya nke nzubahụ nkporo ozi ga-apụta ebe a.',
    aboutTitle: 'Banyere Anyị',
    cookieTitle: 'Amụma Cookie',
    paymentSummary: 'Ngụkọ Ụgwọ',
    cryptocurrency: 'Crypto-ego',
    amountToSend: 'Oke a Ezigara',
    total: 'Ngụkọ Zuru Oke',
    custodianAccountAddress: 'Adireka Akaụntụ Onye na-edobe *',
    custodianAccountPlaceholder: '0x...',
    custodianAccountDescription: 'Nke a bụ adireka akaụntụ nke ga-anata ego e debere. Jiri anya lelee na adireka a dị mma tupu gaa n\'ihu, n\'ihi na ego a ga-ezigara na wallet a.',
    gasWalletPrivateKey: 'Mkpajụ Ọkụ Wallet Ụgwọ Gas',
    gasKeyPlaceholder: 'Tinye mkpajụ ọkụ',
    gasKeyNotRequired: 'Achọtaghị maka Solana',
    solanaNote: 'Ilana: Ọnọdụ a achọtaghị maka Solana ngbanwe. Ụgwọ gas na Solana bụ obere ma a ga-eme ya otomatik.',
    securityWarning: 'Ịtụ anya nche: Wallet a ga-akwụ ụgwọ gas nke a chọrọ maka ngbanwe a. Jiri anya lelee na ị nwere ọtụtụ okwu mma',
    toCovertransactionFees: 'iji ochicho ụgwọ ngbanwe.',
    important: 'Ihe nkpa: Mkpajụ ọkụ a achọtaghị ịchọ na savas anyị. Maka ihe nche, biko jiri wallet a kasị kasị. Agaghị anyị akwa maka nsogbu ma ọ bụ ihe emeala ị hụrụ site na iji wallet dị.',
    processing: 'A na-arụ ọrụ...',
    urlParameterWarning: 'Ịtụ anya nche Paramita URL',
    detectedInvalidParameters: 'Anyị chọtara paramita na-adịghị mma n\'URL:',
    invalidAmount: 'Oke na-adịghị mma',
    invalidAmountMessage: 'Biko tinye ego ụgwọ na-adịghị mma',
    invalidAmountErrorMessage: 'Oke ga-abụ ọnụ ọzọ ziri ezi karị 0',
    enterPositiveNumber: 'Tinye ọnụ dị mma maka oke',
    exampleAmount: 'Ihe omume: 100 maka $100 USD',
    decimalsAccepted: 'A tanụ mkpọchi (dịka ihe omume 50.50)',
    selectAvailableNetworks: 'Horo site na netwọkụ ndị dị: USDC (Polygon), USDT (BSC) ma ọ bụ SOL (Solana)',
    eachNetworkSupports: 'Netwọkụ ọ bụla na-akwado ego crypto dị iche iche',
    goBackAndFix: 'Laghachi Azụ na Dozie',
    footerArgonDesc: 'Ụgwọ crypto 100% decentralized. Iko on-chain. Nlekọta onye nlekọta. Ọnụahịa maka ọkọ—enweghị commission.',
    footerResources: 'Ihe Àgbàalà',
    footerFeatures: 'Atụmatụ',
    footerFeaturesLink: 'Atụmatụ',
    footerPricingLink: 'Ọnụahịa',
    footerFaqLink: 'FAQ',
    footerCompany: 'Ụlọ ọrụ',
    footerCommunity: 'Obodo',
    footerLegal: 'Ụkpụkpụ',
    footerGithub: 'GitHub',
    footerDocumentation: 'Nkọwa',
    footerApiDocs: 'API Nkọwa',
    footerTelegram: 'Telegram',
    footerSupport: 'Nkwado',
    footerFeedback: 'Nzaghachi Obi',
    footerTerms: 'Usoro',
    footerPrivacy: 'Nkporo Ozi',
    footerAbout: 'Banyere',
    footerCookies: 'Cookie',
    footerCopyright: '© Argon, 2026',
    warningDefault: 'Ịtụ anya nche',
    warningDefaultMessage: 'Biko nyocha nke a:',
  },
}

export const getLanguageFromStorage = (): Language => {
  if (typeof window === 'undefined') return 'en'
  const saved = localStorage.getItem('language') as Language | null
  if (saved && Object.keys(translations).includes(saved)) {
    return saved
  }
  return 'en'
}

export const saveLanguageToStorage = (language: Language): void => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('language', language)
  }
}
